import { create } from 'zustand';
import AsyncStorage from '@react-native-async-storage/async-storage';

type Language = 'en' | 'tr' | 'es';

interface LanguageState {
  language: Language;
  setLanguage: (lang: Language) => Promise<void>;
  loadLanguage: () => Promise<void>;
}

export const useLanguageStore = create<LanguageState>((set) => ({
  language: 'en',
  
  setLanguage: async (lang: Language) => {
    try {
      await AsyncStorage.setItem('language', lang);
      set({ language: lang });
    } catch (error) {
      console.error('Error saving language:', error);
    }
  },
  
  loadLanguage: async () => {
    try {
      const savedLang = await AsyncStorage.getItem('language');
      if (savedLang) {
        set({ language: savedLang as Language });
      }
    } catch (error) {
      console.error('Error loading language:', error);
    }
  },
}));

// Translation strings
export const translations = {
  en: {
    // Auth
    login: 'Login',
    register: 'Sign Up',
    email: 'Email',
    password: 'Password',
    username: 'Username',
    fullName: 'Full Name',
    forgotPassword: 'Forgot Password?',
    dontHaveAccount: "Don't have an account? Sign up",
    alreadyHaveAccount: 'Already have an account? Sign in',
    aboutApp: 'About Drivers Chat',
    error: 'Error',
    success: 'Success',
    fillAllFields: 'Please fill in all fields',
    fillAllRequiredFields: 'Please fill in all required fields',
    selectLanguage: 'Select Language',
    passwordMinLength: 'Password must be at least 6 characters',
    passwordMinLengthPlaceholder: 'Password (min. 6 characters)',
    referralCodeOptional: 'Referral Code (optional)',
    creatingAccount: 'Creating account...',
    joinDriverCommunity: 'Join the driver community',
    
    // Tabs
    home: 'Home',
    messages: 'Messages',
    friends: 'Friends',
    profile: 'Profile',
    
    // Common
    post: 'Post',
    send: 'Send',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    settings: 'Settings',
    help: 'Help',
    about: 'About',
    signOut: 'Sign Out',
    loading: 'Loading...',
    
    // Posts
    createPost: 'Create Post',
    newPost: 'New Post',
    editPost: 'Edit Post',
    whatsOnYourMind: "What's on your mind?",
    publishing: 'Publishing...',
    addPhoto: 'Add Photo',
    noPostsYet: 'No posts yet',
    beFirstToPost: 'Be the first to post!',
    postPublished: 'Your post has been published',
    writeError: 'Please write something',
    failedCreatePost: 'Failed to create post',
    postUpdated: 'Post updated successfully',
    failedUpdatePost: 'Failed to update post',
    postDeleted: 'Post deleted successfully',
    failedDeletePost: 'Failed to delete post',
    postRemoved: 'This post was removed due to community feedback',
    
    // Privacy
    whoCanSee: 'Who can see this?',
    publicEveryone: 'Public - Everyone',
    friendsOnly: 'Friends - Only friends',
    specificFriends: 'Specific - Choose friends',
    noFriendsYet: 'No friends yet. Add friends to share with specific people.',
    
    // Delete confirmation
    deletePostTitle: 'Delete Post',
    deletePostMessage: 'Are you sure you want to delete your post?',
    deletePostAdminMessage: 'Are you sure you want to delete this post as an admin?',
    
    // Profile
    viewMyProfile: 'View My Profile',
    yourReferralCode: 'Your Referral Code',
    peopleJoined: 'people joined with your code',
    profilePictureUpdated: 'Profile picture updated successfully!',
    failedUpdatePicture: 'Failed to update profile picture',
    logoutError: 'Failed to sign out. Please try again.',
    
    // Settings
    accountSettings: 'Account Settings',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    updatePassword: 'Update Password',
    deleteAccount: 'Delete Account',
    deleteAccountWarning: 'This action cannot be undone. All your data will be permanently deleted.',
    deleteAccountConfirm: 'Delete My Account',
    language: 'Language',
    passwordUpdated: 'Password updated successfully',
    passwordsDontMatch: 'Passwords do not match',
    accountDeleted: 'Account deleted successfully',
    
    // Help
    helpTitle: 'Help & FAQ',
    helpQuestion1: 'What is Drivers Chat?',
    helpAnswer1: 'Drivers Chat is a social platform designed specifically for Uber and Lyft drivers to connect, share experiences, and communicate with each other.',
    helpQuestion2: 'How do I create a post?',
    helpAnswer2: 'Tap the + button on the home screen. You can write text, add photos, and choose who can see your post (Public, Friends, or Specific friends).',
    helpQuestion3: 'What are likes and dislikes?',
    helpAnswer3: 'You can like (👍) or dislike (👎) posts and comments. If a post gets 10 or more dislikes and dislikes exceed likes, it will be automatically removed.',
    helpQuestion4: 'How do I add friends?',
    helpAnswer4: 'Go to the Friends tab, search for users, and send them a friend request. Once accepted, you can share posts with them.',
    helpQuestion5: 'What is a referral code?',
    helpAnswer5: 'Your unique referral code can be shared with other drivers. When they sign up using your code, you both benefit from being connected!',
    helpQuestion6: 'How do I change my profile picture?',
    helpAnswer6: 'Go to Profile tab and tap on your profile picture to upload a new photo.',
    helpQuestion7: 'How do I contact support?',
    helpAnswer7: 'For support, email us at support@drvchat.com',
    helpHowCanWeHelp: 'How can we help you?',
    helpFindAnswers: 'Find answers to common questions about Drivers Chat',
    helpStillNeed: 'Still need help?',
    helpContactUs: 'Contact us at',
    
    // Help Categories
    helpCategoryAccount: 'Account & Profile',
    helpCategoryFriends: 'Friends System',
    helpCategoryPosts: 'Posts & Sharing',
    helpCategoryMessages: 'Messaging',
    helpCategoryOther: 'Other',
    
    // Help Q&A - Account
    helpQ1: 'How do I register?',
    helpA1: 'On the registration screen, enter your username, email, password, and full name. You can also enter a referral code if you have one. Click "Register" to create your account.',
    helpQ2: 'How do I change my profile picture?',
    helpA2: 'Go to the Profile tab, tap on your profile picture, and select a new photo from your gallery. The photo will be cropped to a square and uploaded automatically.',
    helpQ3: 'What is a referral code?',
    helpA3: 'A referral code is your unique code shown on your profile page. Share it with friends so they can enter it when registering. You\'ll see how many people joined using your code.',
    helpQ4: 'How do I reset my password?',
    helpA4: 'On the login screen, click "Forgot Password?", enter your email and username, and follow the instructions to reset your password.',
    
    // Help Q&A - Friends
    helpQ5: 'How do I add friends?',
    helpA5: 'Go to the Friends tab, use the search bar to find users by username or name, then tap "Add Friend" to send a friend request. You can also add a personal message.',
    helpQ6: 'How do I accept friend requests?',
    helpA6: 'Go to the Friends tab and check the "Friend Requests" section. You\'ll see a badge on the Friends tab icon if you have pending requests. Tap "Accept" or "Decline" for each request.',
    helpQ7: 'Can I remove friends?',
    helpA7: 'Currently, the friend removal feature is not available. This feature will be added in future updates.',
    helpQ8: 'Where can I see my friends list?',
    helpA8: 'Go to the Friends tab and scroll down to see your complete friends list with their profile pictures and names.',
    
    // Help Q&A - Posts
    helpQ9: 'How do I create a post?',
    helpA9: 'On the Home tab, tap the "+" icon in the top right. Write your content, optionally add a photo, choose privacy settings, and tap "Post".',
    helpQ10: 'What are privacy settings?',
    helpA10: 'When creating a post, you can choose:\n• Public: Everyone can see\n• Friends: Only your friends can see\n• Specific: Choose specific friends who can see the post',
    helpQ11: 'How does Like/Dislike work?',
    helpA11: 'You can like 👍 or dislike 👎 any post except your own. Tap the thumbs up to like, or thumbs down to dislike. You can change your vote anytime.',
    helpQ12: 'What happens if a post gets too many dislikes?',
    helpA12: 'If a post receives more than 10 total votes and more than 50% are dislikes, it will be automatically deleted to maintain content quality.',
    helpQ13: 'Can I vote on my own posts?',
    helpA13: 'No, you cannot like or dislike your own posts. The vote buttons will be disabled (grayed out) on your posts.',
    helpQ14: 'How do I view someone\'s profile?',
    helpA14: 'Tap on any username or profile picture in posts or the friends list to view their profile and see all their posts.',
    
    // Help Q&A - Messages
    helpQ15: 'How do I start a chat?',
    helpA15: 'Visit a user\'s profile and tap "Send Message", or go to the Messages tab and select an existing conversation.',
    helpQ16: 'How do I know if I have new messages?',
    helpA16: 'You\'ll see a red badge with the number of unread messages on the Messages tab icon at the bottom.',
    helpQ17: 'Can I send images in chat?',
    helpA17: 'Currently, chat only supports text messages. Image sharing in messages will be added in future updates.',
    helpQ18: 'Are messages real-time?',
    helpA18: 'Yes! Messages use Socket.IO technology for real-time delivery. Messages appear instantly when sent.',
    
    // Help Q&A - Other
    helpQ19: 'How do I sign out?',
    helpA19: 'Go to the Profile tab, scroll down, and tap "Sign Out". Your session will end immediately and you\'ll be redirected to the login screen.',
    helpQ20: 'Can I edit my posts?',
    helpA20: 'Yes! Tap the edit icon (pencil) on your post to edit the content.',
    helpQ21: 'Is my data secure?',
    helpA21: 'Yes! Your password is encrypted, and all API communications are secured. We never share your personal information with third parties.',
    helpQ22: 'Can I use the app offline?',
    helpA22: 'No, this app requires an internet connection to load posts, send messages, and perform all actions.',
    helpQ23: 'Who can see my profile?',
    helpA23: 'All registered users can view your basic profile (name, username, profile picture, posts). Only friends can see posts marked as "Friends only".',
    
    // Settings page
    settingsEditProfile: 'Edit Profile',
    settingsNameBio: 'Name, Bio',
    settingsSecurity: 'Security',
    settingsUpdatePassword: 'Update your password',
    settingsNotifications: 'Notifications',
    settingsFriendRequests: 'Friend Requests',
    settingsGetNotifiedRequests: 'Get notified of new requests',
    settingsGetNotifiedMessages: 'Get notified of new messages',
    settingsLikes: 'Likes',
    settingsGetNotifiedLikes: 'Get notified when someone likes your post',
    settingsGeneral: 'General',
    settingsDarkMode: 'Dark Mode',
    settingsComingSoon: 'Coming soon',
    settingsDangerZone: 'Danger Zone',
    settingsDeleteAccount: 'Delete Account',
    settingsPermanentlyDelete: 'Permanently delete your account',
    settingsProfile: 'Profile',
    settingsSaving: 'Saving...',
    settingsChanging: 'Changing...',
    settingsChange: 'Change',
    settingsEnterName: 'Enter your name',
    settingsBio: 'Bio',
    settingsTellAboutYourself: 'Tell us about yourself',
    settingsEmailReadOnly: 'Email (Read-only)',
    settingsEmailCannotChange: 'Email cannot be changed',
    settingsEnterCurrentPassword: 'Enter current password',
    settingsEnterNewPassword: 'Enter new password',
    settingsReenterNewPassword: 'Re-enter new password',
    settingsPasswordMinChars: 'Password must be at least 6 characters',
    settingsLanguageChanged: 'Language Changed',
    settingsLanguageSetTo: 'Language set to',
    settingsDeleteAccountQuestion: 'Delete Account?',
    settingsDeleteWarning: 'This action cannot be undone. All your posts, messages, and data will be permanently deleted.',
    settingsTypeDelete: 'Type',
    settingsToConfirm: 'to confirm:',
    settingsTypeDeleteHere: 'Type DELETE here',
    settingsDeleteForever: 'Delete Forever',
    settingsNameCannotEmpty: 'Name cannot be empty',
    settingsProfileUpdated: 'Profile updated successfully!',
    settingsFailedUpdateProfile: 'Failed to update profile',
    settingsNewPasswordsNoMatch: 'New passwords do not match',
    settingsFailedChangePassword: 'Failed to change password',
    settingsPasswordChanged: 'Password changed successfully!',
    settingsAccountDeleted: 'Your account has been permanently deleted',
    settingsFailedDeleteAccount: 'Failed to delete account',
    settingsPleaseTypeDelete: 'Please type DELETE to confirm',
    
    // Messages/Chat
    messagesNoMessagesYet: 'No messages yet',
    messagesStartChatting: 'Start chatting!',
    messagesNewChat: 'New Chat',
    
    // Friends
    friendsTitle: 'Friends',
    friendsSearchDrivers: 'Search drivers...',
    friendsFriendRequests: 'Friend Requests',
    friendsMyFriends: 'My Friends',
    friendsNoFriendsYet: 'No friends yet',
    friendsSearchAddFriends: 'Search and add friends above!',
    friendsFriendRequestSent: 'Friend request sent!',
    friendsFailedSendRequest: 'Failed to send request',
    friendsFriendAdded: 'Friend added!',
    friendsRequestRejected: 'Request rejected',
    friendsActionFailed: 'Action failed',
    
    // Forgot Password
    forgotPasswordTitle: 'Forgot Password',
    forgotPasswordInstruction: 'Enter your email and username to reset your password',
    forgotPasswordResetButton: 'Reset Password',
    forgotPasswordCheckEmail: 'Check Your Email',
    forgotPasswordEmailSent: 'Password reset instructions have been sent to your email.',
    forgotPasswordBackToLogin: 'Back to Login',
    forgotPasswordFailed: 'Failed to send reset email',
    
    // Post Detail
    postDetailComments: 'Comments',
    postDetailNoComments: 'No comments yet',
    postDetailBeFirst: 'Be the first to comment!',
    postDetailWriteComment: 'Write a comment...',
    postDetailSendComment: 'Send',
    postDetailCommentPosted: 'Comment posted!',
    postDetailFailedComment: 'Failed to post comment',
    
    // Profile Detail
    profileDetailSendMessage: 'Send Message',
    profileDetailAddFriend: 'Add Friend',
    profileDetailPosts: 'Posts',
    profileDetailNoPosts: 'No posts yet',
    
    // Edit Post Modal
    editPostSaveChanges: 'Save Changes',
    
    // Full Screen Image
    fullScreenImageClose: 'Close',
    
    // About
    aboutTitle: 'About Drivers Chat',
    aboutDescription: 'Drivers Chat is a community platform built by drivers, for drivers. Connect with fellow Uber and Lyft drivers, share your experiences, and build meaningful connections.',
    aboutVersion: 'Version',
    aboutSupport: 'Support',
    aboutTerms: 'Terms & Conditions',
    viewTerms: 'View Terms & Conditions',
    
    // Terms Modal
    termsTitle: 'Terms & Conditions',
    termsOfService: 'Terms of Service',
    communityGuidelines: 'Community Guidelines',
    termsAccept: 'I Accept',
    termsDecline: 'Decline',
    termsStep: 'Step',
    termsOf: 'of',
    termsAgreeService: 'I have read and agree to the Terms of Service',
    termsAgreeGuidelines: 'I have read and agree to follow the Community Guidelines',
    termsContinue: 'Continue',
    termsAcceptStart: 'Accept & Start Using Drivers Chat',
    termsEffectiveDate: 'Effective Date: January 2025',
    termsWelcome: 'Welcome to Drivers Chat! Please read these terms carefully before using our application.',
    termsNonCommercial: 'Non-Commercial Application',
    termsLimitationLiability: 'Limitation of Liability',
    termsYourRights: 'Your Rights & Account Control',
    termsDataPrivacy: 'Data & Privacy',
    termsAgeRequirement: 'Age Requirement',
    termsAccountSecurity: 'Account Security',
    termsServiceChanges: 'Service Changes & Termination',
    termsContact: 'Contact',
    termsSupportEmail: 'support@drvchat.com',
    guidelinesKeepSafe: 'Keep Drivers Chat Safe & Respectful',
    guidelinesIntro: 'These guidelines ensure a positive experience for all members. Violations will result in account suspension or permanent ban.',
    guidelinesProhibited: 'Strictly Prohibited Content',
    guidelinesConsequences: 'Consequences',
    guidelinesWhatYouCan: 'What You CAN Share',
    guidelinesReport: 'Report Violations',
    
    // About page
    aboutWherDriversConnect: 'Where Drivers Connect',
    aboutTheApp: 'About the App',
    aboutAppDescription: 'Drivers Chat is a FREE social platform built exclusively for Uber and Lyft drivers. Connect with fellow drivers, share experiences, get tips, and stay informed about everything related to rideshare driving.',
    aboutOurMission: 'Our Mission',
    aboutMissionDescription: 'To create a supportive community where rideshare drivers can connect, share knowledge, and help each other navigate the challenges and opportunities of driving for Uber and Lyft.',
    aboutKeyFeatures: 'Key Features',
    aboutFeature1: 'Connect with drivers nationwide',
    aboutFeature2: 'Real-time messaging',
    aboutFeature3: 'Share tips and experiences',
    aboutFeature4: 'Community-driven content moderation',
    aboutFeature5: 'Referral rewards system',
    aboutFeature6: 'Safe and respectful community',
    aboutFree: '100% Free',
    aboutFreeDescription: 'Drivers Chat is completely free with no paid memberships, premium features, or hidden costs. This is a non-commercial platform built by drivers, for drivers.',
    aboutCommunityGuidelines: 'Community Guidelines',
    aboutGuidelinesDescription: 'We maintain a safe and respectful environment by prohibiting commercial activities, political content, gambling, adult content, hate speech, and illegal activities. Users who violate our guidelines face account suspension or permanent bans.',
    aboutReadFullTerms: 'Read Full Terms & Guidelines →',
    aboutContactSupport: 'Contact & Support',
    aboutContactDescription: 'Have questions, feedback, or need help?',
    aboutEmailUs: 'Email us at:',
    aboutVisitHelp: 'Visit Help Center →',
    aboutLegal: 'Legal',
    aboutTermsService: 'Terms of Service',
    aboutPrivacyPolicy: 'Privacy Policy',
    aboutMadeWith: 'Made with ❤️ for rideshare drivers',
    aboutCopyright: '© 2025 Drivers Chat. All rights reserved.',
    aboutLegalGuidelines: 'Legal & Guidelines',
  },
  tr: {
    // Auth
    login: 'Giriş Yap',
    register: 'Kayıt Ol',
    email: 'E-posta',
    password: 'Şifre',
    username: 'Kullanıcı Adı',
    fullName: 'Ad Soyad',
    forgotPassword: 'Şifremi Unuttum?',
    dontHaveAccount: 'Hesabınız yok mu? Kayıt olun',
    alreadyHaveAccount: 'Zaten hesabınız var mı? Giriş yapın',
    aboutApp: 'Drivers Chat Hakkında',
    error: 'Hata',
    success: 'Başarılı',
    fillAllFields: 'Lütfen tüm alanları doldurun',
    fillAllRequiredFields: 'Lütfen tüm gerekli alanları doldurun',
    selectLanguage: 'Dil Seçin',
    passwordMinLength: 'Şifre en az 6 karakter olmalıdır',
    passwordMinLengthPlaceholder: 'Şifre (min. 6 karakter)',
    referralCodeOptional: 'Referans Kodu (isteğe bağlı)',
    creatingAccount: 'Hesap oluşturuluyor...',
    joinDriverCommunity: 'Sürücü topluluğuna katılın',
    
    // Tabs
    home: 'Ana Sayfa',
    messages: 'Mesajlar',
    friends: 'Arkadaşlar',
    profile: 'Profil',
    
    // Common
    post: 'Paylaş',
    send: 'Gönder',
    cancel: 'İptal',
    save: 'Kaydet',
    delete: 'Sil',
    edit: 'Düzenle',
    settings: 'Ayarlar',
    help: 'Yardım',
    about: 'Hakkında',
    signOut: 'Çıkış Yap',
    loading: 'Yükleniyor...',
    
    // Posts
    createPost: 'Gönderi Oluştur',
    newPost: 'Yeni Gönderi',
    editPost: 'Gönderiyi Düzenle',
    whatsOnYourMind: 'Ne düşünüyorsun?',
    publishing: 'Yayınlanıyor...',
    addPhoto: 'Fotoğraf Ekle',
    noPostsYet: 'Henüz gönderi yok',
    beFirstToPost: 'İlk paylaşan sen ol!',
    postPublished: 'Gönderiniz yayınlandı',
    writeError: 'Lütfen bir şeyler yazın',
    failedCreatePost: 'Gönderi oluşturulamadı',
    postUpdated: 'Gönderi başarıyla güncellendi',
    failedUpdatePost: 'Gönderi güncellenemedi',
    postDeleted: 'Gönderi başarıyla silindi',
    failedDeletePost: 'Gönderi silinemedi',
    postRemoved: 'Bu gönderi topluluk geri bildirimi nedeniyle kaldırıldı',
    
    // Privacy
    whoCanSee: 'Bunu kimler görebilir?',
    publicEveryone: 'Herkese Açık',
    friendsOnly: 'Arkadaşlar - Sadece arkadaşlar',
    specificFriends: 'Belirli Kişiler - Arkadaşları seç',
    noFriendsYet: 'Henüz arkadaş yok. Belirli kişilerle paylaşmak için arkadaş ekleyin.',
    
    // Delete confirmation
    deletePostTitle: 'Gönderiyi Sil',
    deletePostMessage: 'Gönderinizi silmek istediğinizden emin misiniz?',
    deletePostAdminMessage: 'Yönetici olarak bu gönderiyi silmek istediğinizden emin misiniz?',
    
    // Profile
    viewMyProfile: 'Profilimi Görüntüle',
    yourReferralCode: 'Referans Kodunuz',
    peopleJoined: 'kişi kodunuzla katıldı',
    profilePictureUpdated: 'Profil resmi başarıyla güncellendi!',
    failedUpdatePicture: 'Profil resmi güncellenemedi',
    logoutError: 'Çıkış yapılamadı. Lütfen tekrar deneyin.',
    
    // Settings
    accountSettings: 'Hesap Ayarları',
    changePassword: 'Şifre Değiştir',
    currentPassword: 'Mevcut Şifre',
    newPassword: 'Yeni Şifre',
    confirmPassword: 'Şifreyi Onayla',
    updatePassword: 'Şifreyi Güncelle',
    deleteAccount: 'Hesabı Sil',
    deleteAccountWarning: 'Bu işlem geri alınamaz. Tüm verileriniz kalıcı olarak silinecektir.',
    deleteAccountConfirm: 'Hesabımı Sil',
    language: 'Dil',
    passwordUpdated: 'Şifre başarıyla güncellendi',
    passwordsDontMatch: 'Şifreler eşleşmiyor',
    accountDeleted: 'Hesap başarıyla silindi',
    
    // Help
    helpTitle: 'Yardım & SSS',
    helpQuestion1: 'Drivers Chat nedir?',
    helpAnswer1: 'Drivers Chat, Uber ve Lyft sürücüleri için özel olarak tasarlanmış bir sosyal platformdur. Sürücüler birbirleriyle bağlantı kurabilir, deneyimlerini paylaşabilir ve iletişim kurabilir.',
    helpQuestion2: 'Nasıl gönderi oluştururum?',
    helpAnswer2: 'Ana ekrandaki + butonuna dokunun. Metin yazabilir, fotoğraf ekleyebilir ve gönderinizi kimin görebileceğini seçebilirsiniz (Herkese Açık, Arkadaşlar veya Belirli arkadaşlar).',
    helpQuestion3: 'Beğeni ve beğenmeme nedir?',
    helpAnswer3: 'Gönderileri ve yorumları beğenebilir (👍) veya beğenmeyebilirsiniz (👎). Bir gönderi 10 veya daha fazla beğenmeme alırsa ve beğenmeme sayısı beğeni sayısını geçerse, otomatik olarak kaldırılır.',
    helpQuestion4: 'Nasıl arkadaş eklerim?',
    helpAnswer4: 'Arkadaşlar sekmesine gidin, kullanıcıları arayın ve arkadaşlık isteği gönderin. Kabul edildikten sonra onlarla gönderi paylaşabilirsiniz.',
    helpQuestion5: 'Referans kodu nedir?',
    helpAnswer5: 'Benzersiz referans kodunuzu diğer sürücülerle paylaşabilirsiniz. Kodunuzu kullanarak kayıt olduklarında, her ikiniz de bağlantılı olmaktan faydalanırsınız!',
    helpQuestion6: 'Profil resmimi nasıl değiştirebilirim?',
    helpAnswer6: 'Profil sekmesine gidin ve yeni bir fotoğraf yüklemek için profil resminize dokunun.',
    helpQuestion7: 'Desteğe nasıl ulaşabilirim?',
    helpAnswer7: 'Destek için bize support@drvchat.com adresinden e-posta gönderin',
    helpHowCanWeHelp: 'Nasıl yardımcı olabiliriz?',
    helpFindAnswers: 'Drivers Chat hakkında sık sorulan sorulara cevaplar bulun',
    helpStillNeed: 'Hala yardıma mı ihtiyacınız var?',
    helpContactUs: 'Bize ulaşın:',
    
    // Help Categories
    helpCategoryAccount: 'Hesap & Profil',
    helpCategoryFriends: 'Arkadaş Sistemi',
    helpCategoryPosts: 'Gönderiler & Paylaşım',
    helpCategoryMessages: 'Mesajlaşma',
    helpCategoryOther: 'Diğer',
    
    // Help Q&A - Account
    helpQ1: 'Nasıl kayıt olurum?',
    helpA1: 'Kayıt ekranında kullanıcı adınızı, e-postanızı, şifrenizi ve tam adınızı girin. Varsa bir referans kodu da girebilirsiniz. Hesabınızı oluşturmak için "Kayıt Ol"a tıklayın.',
    helpQ2: 'Profil resmimi nasıl değiştiririm?',
    helpA2: 'Profil sekmesine gidin, profil resminize dokunun ve galerinizden yeni bir fotoğraf seçin. Fotoğraf kareye kırpılacak ve otomatik olarak yüklenecektir.',
    helpQ3: 'Referans kodu nedir?',
    helpA3: 'Referans kodu, profil sayfanızda gösterilen benzersiz kodunuzdur. Arkadaşlarınızla paylaşın, böylece kayıt olurken girebilirler. Kodunuzla kaç kişinin katıldığını göreceksiniz.',
    helpQ4: 'Şifremi nasıl sıfırlarım?',
    helpA4: 'Giriş ekranında "Şifremi Unuttum?"a tıklayın, e-postanızı ve kullanıcı adınızı girin ve şifrenizi sıfırlamak için talimatları izleyin.',
    
    // Help Q&A - Friends
    helpQ5: 'Nasıl arkadaş eklerim?',
    helpA5: 'Arkadaşlar sekmesine gidin, kullanıcı adı veya ada göre kullanıcıları bulmak için arama çubuğunu kullanın, ardından arkadaşlık isteği göndermek için "Arkadaş Ekle"ye dokunun. Kişisel bir mesaj da ekleyebilirsiniz.',
    helpQ6: 'Arkadaşlık isteklerini nasıl kabul ederim?',
    helpA6: 'Arkadaşlar sekmesine gidin ve "Arkadaşlık İstekleri" bölümünü kontrol edin. Bekleyen istekleriniz varsa Arkadaşlar sekmesi simgesinde bir rozet göreceksiniz. Her istek için "Kabul Et" veya "Reddet"e dokunun.',
    helpQ7: 'Arkadaşları kaldırabilir miyim?',
    helpA7: 'Şu anda arkadaş kaldırma özelliği mevcut değil. Bu özellik gelecek güncellemelerde eklenecektir.',
    helpQ8: 'Arkadaş listemi nerede görebilirim?',
    helpA8: 'Arkadaşlar sekmesine gidin ve profil resimleri ve isimleri ile tüm arkadaş listenizi görmek için aşağı kaydırın.',
    
    // Help Q&A - Posts
    helpQ9: 'Nasıl gönderi oluştururum?',
    helpA9: 'Ana Sayfa sekmesinde sağ üstteki "+" simgesine dokunun. İçeriğinizi yazın, isteğe bağlı olarak bir fotoğraf ekleyin, gizlilik ayarlarını seçin ve "Paylaş"a dokunun.',
    helpQ10: 'Gizlilik ayarları nedir?',
    helpA10: 'Gönderi oluştururken şunları seçebilirsiniz:\n• Herkese Açık: Herkes görebilir\n• Arkadaşlar: Sadece arkadaşlarınız görebilir\n• Belirli: Gönderiyi görebilecek belirli arkadaşları seçin',
    helpQ11: 'Beğeni/Beğenmeme nasıl çalışır?',
    helpA11: 'Kendinizinkiler hariç herhangi bir gönderiyi beğenebilir 👍 veya beğenmeyebilirsiniz 👎. Beğenmek için başparmak yukarı, beğenmemek için başparmak aşağıya dokunun. Oyunuzu istediğiniz zaman değiştirebilirsiniz.',
    helpQ12: 'Bir gönderi çok fazla beğenmeme alırsa ne olur?',
    helpA12: '10\'dan fazla toplam oy alan ve %50\'den fazlası beğenmeme olan bir gönderi, içerik kalitesini korumak için otomatik olarak silinir.',
    helpQ13: 'Kendi gönderilerime oy verebilir miyim?',
    helpA13: 'Hayır, kendi gönderilerinizi beğenemez veya beğenmeyemezsiniz. Oy butonları gönderilerinizde devre dışı (gri) olacaktır.',
    helpQ14: 'Birinin profilini nasıl görüntülerim?',
    helpA14: 'Gönderilerdeki veya arkadaş listesindeki herhangi bir kullanıcı adına veya profil resmine dokunarak profillerini görüntüleyin ve tüm gönderilerini görün.',
    
    // Help Q&A - Messages
    helpQ15: 'Nasıl sohbet başlatırım?',
    helpA15: 'Bir kullanıcının profilini ziyaret edin ve "Mesaj Gönder"e dokunun veya Mesajlar sekmesine gidin ve mevcut bir konuşmayı seçin.',
    helpQ16: 'Yeni mesajlarım olduğunu nasıl anlarım?',
    helpA16: 'Alttaki Mesajlar sekmesi simgesinde okunmamış mesaj sayısını gösteren kırmızı bir rozet göreceksiniz.',
    helpQ17: 'Sohbette resim gönderebilir miyim?',
    helpA17: 'Şu anda sohbet yalnızca metin mesajlarını destekliyor. Mesajlarda resim paylaşımı gelecek güncellemelerde eklenecektir.',
    helpQ18: 'Mesajlar gerçek zamanlı mı?',
    helpA18: 'Evet! Mesajlar gerçek zamanlı teslimat için Socket.IO teknolojisini kullanır. Mesajlar gönderildiğinde anında görünür.',
    
    // Help Q&A - Other
    helpQ19: 'Nasıl çıkış yaparım?',
    helpA19: 'Profil sekmesine gidin, aşağı kaydırın ve "Çıkış Yap"a dokunun. Oturumunuz hemen sona erecek ve giriş ekranına yönlendirileceksiniz.',
    helpQ20: 'Gönderilerimi düzenleyebilir miyim?',
    helpA20: 'Evet! İçeriği düzenlemek için gönderinizdeki düzenle simgesine (kalem) dokunun.',
    helpQ21: 'Verilerim güvende mi?',
    helpA21: 'Evet! Şifreniz şifrelenir ve tüm API iletişimleri güvenlidir. Kişisel bilgilerinizi asla üçüncü taraflarla paylaşmayız.',
    helpQ22: 'Uygulamayı çevrimdışı kullanabilir miyim?',
    helpA22: 'Hayır, bu uygulama gönderileri yüklemek, mesaj göndermek ve tüm işlemleri gerçekleştirmek için internet bağlantısı gerektirir.',
    helpQ23: 'Profilimi kimler görebilir?',
    helpA23: 'Tüm kayıtlı kullanıcılar temel profilinizi (ad, kullanıcı adı, profil resmi, gönderiler) görüntüleyebilir. Sadece arkadaşlar "Sadece arkadaşlar" olarak işaretlenmiş gönderileri görebilir.',
    
    // About
    aboutTitle: 'Drivers Chat Hakkında',
    aboutDescription: 'Drivers Chat, sürücüler tarafından sürücüler için oluşturulmuş bir topluluk platformudur. Diğer Uber ve Lyft sürücüleriyle bağlantı kurun, deneyimlerinizi paylaşın ve anlamlı bağlantılar oluşturun.',
    aboutVersion: 'Versiyon',
    aboutSupport: 'Destek',
    aboutTerms: 'Şartlar & Koşullar',
    viewTerms: 'Şartlar & Koşulları Görüntüle',
    
    // Terms Modal
    termsTitle: 'Şartlar & Koşullar',
    termsOfService: 'Hizmet Şartları',
    communityGuidelines: 'Topluluk Kuralları',
    termsAccept: 'Kabul Ediyorum',
    termsDecline: 'Reddet',
    termsStep: 'Adım',
    termsOf: '/  ',
    termsAgreeService: 'Hizmet Şartlarını okudum ve kabul ediyorum',
    termsAgreeGuidelines: 'Topluluk Kurallarını okudum ve uyacağımı kabul ediyorum',
    termsContinue: 'Devam Et',
    termsAcceptStart: 'Kabul Et & Drivers Chat Kullanmaya Başla',
    termsEffectiveDate: 'Yürürlük Tarihi: Ocak 2025',
    termsWelcome: 'Drivers Chat\'e hoş geldiniz! Uygulamamızı kullanmadan önce lütfen bu şartları dikkatle okuyun.',
    termsNonCommercial: 'Ticari Olmayan Uygulama',
    termsLimitationLiability: 'Sorumluluk Sınırlaması',
    termsYourRights: 'Haklarınız & Hesap Kontrolü',
    termsDataPrivacy: 'Veri & Gizlilik',
    termsAgeRequirement: 'Yaş Gereksinimi',
    termsAccountSecurity: 'Hesap Güvenliği',
    termsServiceChanges: 'Hizmet Değişiklikleri & Sonlandırma',
    termsContact: 'İletişim',
    termsSupportEmail: 'support@drvchat.com',
    guidelinesKeepSafe: 'Drivers Chat\'i Güvenli & Saygılı Tutun',
    guidelinesIntro: 'Bu kurallar tüm üyeler için olumlu bir deneyim sağlar. İhlaller hesap askıya alınması veya kalıcı yasakla sonuçlanır.',
    guidelinesProhibited: 'Kesinlikle Yasak İçerik',
    guidelinesConsequences: 'Sonuçlar',
    guidelinesWhatYouCan: 'Paylaşabilecekleriniz',
    guidelinesReport: 'İhlalleri Bildirin',
    
    // About page
    aboutWherDriversConnect: 'Sürücülerin Buluştuğu Yer',
    aboutTheApp: 'Uygulama Hakkında',
    aboutAppDescription: 'Drivers Chat, Uber ve Lyft sürücüleri için özel olarak oluşturulmuş ÜCRETSİZ bir sosyal platformdur. Diğer sürücülerle bağlantı kurun, deneyimleri paylaşın, ipuçları alın ve rideshare sürücülüğüyle ilgili her şeyden haberdar olun.',
    aboutOurMission: 'Misyonumuz',
    aboutMissionDescription: 'Rideshare sürücülerinin bağlantı kurabilecekleri, bilgi paylaşabilecekleri ve Uber ve Lyft için sürücülük yapmanın zorlukları ve fırsatlarında birbirlerine yardımcı olabilecekleri destekleyici bir topluluk oluşturmak.',
    aboutKeyFeatures: 'Temel Özellikler',
    aboutFeature1: 'Ülke çapında sürücülerle bağlantı kurun',
    aboutFeature2: 'Gerçek zamanlı mesajlaşma',
    aboutFeature3: 'İpuçları ve deneyimleri paylaşın',
    aboutFeature4: 'Topluluk odaklı içerik moderasyonu',
    aboutFeature5: 'Referans ödül sistemi',
    aboutFeature6: 'Güvenli ve saygılı topluluk',
    aboutFree: '100% Ücretsiz',
    aboutFreeDescription: 'Drivers Chat, ücretli üyelikler, premium özellikler veya gizli maliyetler olmadan tamamen ücretsizdir. Bu, sürücüler tarafından sürücüler için oluşturulmuş ticari olmayan bir platformdur.',
    aboutCommunityGuidelines: 'Topluluk Kuralları',
    aboutGuidelinesDescription: 'Ticari faaliyetleri, siyasi içeriği, kumar, yetişkinlere yönelik içerik, nefret söylemi ve yasadışı faaliyetleri yasaklayarak güvenli ve saygılı bir ortam sağlıyoruz. Kurallarımızı ihlal eden kullanıcılar hesap askıya alınması veya kalıcı yasaklarla karşı karşıya kalır.',
    aboutReadFullTerms: 'Tam Şartlar & Kuralları Okuyun →',
    aboutContactSupport: 'İletişim & Destek',
    aboutContactDescription: 'Sorularınız, geri bildiriminiz veya yardıma mı ihtiyacınız var?',
    aboutEmailUs: 'Bize e-posta gönderin:',
    aboutVisitHelp: 'Yardım Merkezini Ziyaret Edin →',
    aboutLegal: 'Yasal',
    aboutTermsService: 'Hizmet Şartları',
    aboutPrivacyPolicy: 'Gizlilik Politikası',
    aboutMadeWith: 'Rideshare sürücüleri için ❤️ ile yapıldı',
    aboutCopyright: '© 2025 Drivers Chat. Tüm hakları saklıdır.',
    aboutLegalGuidelines: 'Yasal & Kurallar',
  },
  es: {
    // Auth
    login: 'Iniciar Sesión',
    register: 'Registrarse',
    email: 'Correo Electrónico',
    password: 'Contraseña',
    username: 'Nombre de Usuario',
    fullName: 'Nombre Completo',
    forgotPassword: '¿Olvidaste tu contraseña?',
    dontHaveAccount: '¿No tienes cuenta? Regístrate',
    alreadyHaveAccount: '¿Ya tienes cuenta? Inicia sesión',
    aboutApp: 'Acerca de Drivers Chat',
    error: 'Error',
    success: 'Éxito',
    fillAllFields: 'Por favor completa todos los campos',
    fillAllRequiredFields: 'Por favor completa todos los campos requeridos',
    selectLanguage: 'Seleccionar Idioma',
    passwordMinLength: 'La contraseña debe tener al menos 6 caracteres',
    passwordMinLengthPlaceholder: 'Contraseña (mín. 6 caracteres)',
    referralCodeOptional: 'Código de Referencia (opcional)',
    creatingAccount: 'Creando cuenta...',
    joinDriverCommunity: 'Únete a la comunidad de conductores',
    
    // Tabs
    home: 'Inicio',
    messages: 'Mensajes',
    friends: 'Amigos',
    profile: 'Perfil',
    
    // Common
    post: 'Publicar',
    send: 'Enviar',
    cancel: 'Cancelar',
    save: 'Guardar',
    delete: 'Eliminar',
    edit: 'Editar',
    settings: 'Configuración',
    help: 'Ayuda',
    about: 'Acerca de',
    signOut: 'Cerrar Sesión',
    loading: 'Cargando...',
    
    // Posts
    createPost: 'Crear Publicación',
    newPost: 'Nueva Publicación',
    editPost: 'Editar Publicación',
    whatsOnYourMind: '¿Qué estás pensando?',
    publishing: 'Publicando...',
    addPhoto: 'Agregar Foto',
    noPostsYet: 'Aún no hay publicaciones',
    beFirstToPost: '¡Sé el primero en publicar!',
    postPublished: 'Tu publicación ha sido publicada',
    writeError: 'Por favor escribe algo',
    failedCreatePost: 'Error al crear publicación',
    postUpdated: 'Publicación actualizada exitosamente',
    failedUpdatePost: 'Error al actualizar publicación',
    postDeleted: 'Publicación eliminada exitosamente',
    failedDeletePost: 'Error al eliminar publicación',
    postRemoved: 'Esta publicación fue eliminada debido a comentarios de la comunidad',
    
    // Privacy
    whoCanSee: '¿Quién puede ver esto?',
    publicEveryone: 'Público - Todos',
    friendsOnly: 'Amigos - Solo amigos',
    specificFriends: 'Específico - Elegir amigos',
    noFriendsYet: 'Aún no tienes amigos. Agrega amigos para compartir con personas específicas.',
    
    // Delete confirmation
    deletePostTitle: 'Eliminar Publicación',
    deletePostMessage: '¿Estás seguro de que quieres eliminar tu publicación?',
    deletePostAdminMessage: '¿Estás seguro de que quieres eliminar esta publicación como administrador?',
    
    // Profile
    viewMyProfile: 'Ver Mi Perfil',
    yourReferralCode: 'Tu Código de Referencia',
    peopleJoined: 'personas se unieron con tu código',
    profilePictureUpdated: '¡Foto de perfil actualizada exitosamente!',
    failedUpdatePicture: 'Error al actualizar foto de perfil',
    logoutError: 'Error al cerrar sesión. Por favor intenta de nuevo.',
    
    // Settings
    accountSettings: 'Configuración de Cuenta',
    changePassword: 'Cambiar Contraseña',
    currentPassword: 'Contraseña Actual',
    newPassword: 'Nueva Contraseña',
    confirmPassword: 'Confirmar Contraseña',
    updatePassword: 'Actualizar Contraseña',
    deleteAccount: 'Eliminar Cuenta',
    deleteAccountWarning: 'Esta acción no se puede deshacer. Todos tus datos serán eliminados permanentemente.',
    deleteAccountConfirm: 'Eliminar Mi Cuenta',
    language: 'Idioma',
    passwordUpdated: 'Contraseña actualizada exitosamente',
    passwordsDontMatch: 'Las contraseñas no coinciden',
    accountDeleted: 'Cuenta eliminada exitosamente',
    
    // Help
    helpTitle: 'Ayuda & Preguntas Frecuentes',
    helpQuestion1: '¿Qué es Drivers Chat?',
    helpAnswer1: 'Drivers Chat es una plataforma social diseñada específicamente para conductores de Uber y Lyft para conectarse, compartir experiencias y comunicarse entre sí.',
    helpQuestion2: '¿Cómo creo una publicación?',
    helpAnswer2: 'Toca el botón + en la pantalla de inicio. Puedes escribir texto, agregar fotos y elegir quién puede ver tu publicación (Público, Amigos o Amigos específicos).',
    helpQuestion3: '¿Qué son los me gusta y no me gusta?',
    helpAnswer3: 'Puedes dar me gusta (👍) o no me gusta (👎) a publicaciones y comentarios. Si una publicación recibe 10 o más no me gusta y los no me gusta superan los me gusta, se eliminará automáticamente.',
    helpQuestion4: '¿Cómo agrego amigos?',
    helpAnswer4: 'Ve a la pestaña Amigos, busca usuarios y envíales una solicitud de amistad. Una vez aceptada, puedes compartir publicaciones con ellos.',
    helpQuestion5: '¿Qué es un código de referencia?',
    helpAnswer5: 'Tu código de referencia único puede compartirse con otros conductores. ¡Cuando se registren usando tu código, ambos se beneficiarán de estar conectados!',
    helpQuestion6: '¿Cómo cambio mi foto de perfil?',
    helpAnswer6: 'Ve a la pestaña Perfil y toca tu foto de perfil para subir una nueva foto.',
    helpQuestion7: '¿Cómo contacto con soporte?',
    helpAnswer7: 'Para soporte, envíanos un correo a support@drvchat.com',
    helpHowCanWeHelp: '¿Cómo podemos ayudarte?',
    helpFindAnswers: 'Encuentra respuestas a preguntas comunes sobre Drivers Chat',
    helpStillNeed: '¿Aún necesitas ayuda?',
    helpContactUs: 'Contáctanos en',
    
    // Help Categories
    helpCategoryAccount: 'Cuenta & Perfil',
    helpCategoryFriends: 'Sistema de Amigos',
    helpCategoryPosts: 'Publicaciones & Compartir',
    helpCategoryMessages: 'Mensajería',
    helpCategoryOther: 'Otro',
    
    // Help Q&A - Account
    helpQ1: '¿Cómo me registro?',
    helpA1: 'En la pantalla de registro, ingresa tu nombre de usuario, correo electrónico, contraseña y nombre completo. También puedes ingresar un código de referencia si tienes uno. Haz clic en "Registrarse" para crear tu cuenta.',
    helpQ2: '¿Cómo cambio mi foto de perfil?',
    helpA2: 'Ve a la pestaña Perfil, toca tu foto de perfil y selecciona una nueva foto de tu galería. La foto se recortará en un cuadrado y se subirá automáticamente.',
    helpQ3: '¿Qué es un código de referencia?',
    helpA3: 'Un código de referencia es tu código único que se muestra en tu página de perfil. Compártelo con amigos para que puedan ingresarlo al registrarse. Verás cuántas personas se unieron usando tu código.',
    helpQ4: '¿Cómo restablezco mi contraseña?',
    helpA4: 'En la pantalla de inicio de sesión, haz clic en "¿Olvidaste tu contraseña?", ingresa tu correo electrónico y nombre de usuario, y sigue las instrucciones para restablecer tu contraseña.',
    
    // Help Q&A - Friends
    helpQ5: '¿Cómo agrego amigos?',
    helpA5: 'Ve a la pestaña Amigos, usa la barra de búsqueda para encontrar usuarios por nombre de usuario o nombre, luego toca "Agregar Amigo" para enviar una solicitud de amistad. También puedes agregar un mensaje personal.',
    helpQ6: '¿Cómo acepto solicitudes de amistad?',
    helpA6: 'Ve a la pestaña Amigos y verifica la sección "Solicitudes de Amistad". Verás una insignia en el ícono de la pestaña Amigos si tienes solicitudes pendientes. Toca "Aceptar" o "Rechazar" para cada solicitud.',
    helpQ7: '¿Puedo eliminar amigos?',
    helpA7: 'Actualmente, la función de eliminación de amigos no está disponible. Esta función se agregará en futuras actualizaciones.',
    helpQ8: '¿Dónde puedo ver mi lista de amigos?',
    helpA8: 'Ve a la pestaña Amigos y desplázate hacia abajo para ver tu lista completa de amigos con sus fotos de perfil y nombres.',
    
    // Help Q&A - Posts
    helpQ9: '¿Cómo creo una publicación?',
    helpA9: 'En la pestaña Inicio, toca el ícono "+" en la parte superior derecha. Escribe tu contenido, opcionalmente agrega una foto, elige la configuración de privacidad y toca "Publicar".',
    helpQ10: '¿Qué son las configuraciones de privacidad?',
    helpA10: 'Al crear una publicación, puedes elegir:\n• Público: Todos pueden ver\n• Amigos: Solo tus amigos pueden ver\n• Específico: Elige amigos específicos que puedan ver la publicación',
    helpQ11: '¿Cómo funciona Me gusta/No me gusta?',
    helpA11: 'Puedes dar me gusta 👍 o no me gusta 👎 a cualquier publicación excepto la tuya. Toca el pulgar hacia arriba para dar me gusta o el pulgar hacia abajo para no me gusta. Puedes cambiar tu voto en cualquier momento.',
    helpQ12: '¿Qué pasa si una publicación recibe demasiados no me gusta?',
    helpA12: 'Si una publicación recibe más de 10 votos totales y más del 50% son no me gusta, se eliminará automáticamente para mantener la calidad del contenido.',
    helpQ13: '¿Puedo votar en mis propias publicaciones?',
    helpA13: 'No, no puedes dar me gusta o no me gusta a tus propias publicaciones. Los botones de votación estarán deshabilitados (en gris) en tus publicaciones.',
    helpQ14: '¿Cómo veo el perfil de alguien?',
    helpA14: 'Toca cualquier nombre de usuario o foto de perfil en publicaciones o la lista de amigos para ver su perfil y ver todas sus publicaciones.',
    
    // Help Q&A - Messages
    helpQ15: '¿Cómo inicio un chat?',
    helpA15: 'Visita el perfil de un usuario y toca "Enviar Mensaje", o ve a la pestaña Mensajes y selecciona una conversación existente.',
    helpQ16: '¿Cómo sé si tengo mensajes nuevos?',
    helpA16: 'Verás una insignia roja con el número de mensajes no leídos en el ícono de la pestaña Mensajes en la parte inferior.',
    helpQ17: '¿Puedo enviar imágenes en el chat?',
    helpA17: 'Actualmente, el chat solo admite mensajes de texto. El compartir imágenes en mensajes se agregará en futuras actualizaciones.',
    helpQ18: '¿Los mensajes son en tiempo real?',
    helpA18: '¡Sí! Los mensajes usan tecnología Socket.IO para entrega en tiempo real. Los mensajes aparecen instantáneamente cuando se envían.',
    
    // Help Q&A - Other
    helpQ19: '¿Cómo cierro sesión?',
    helpA19: 'Ve a la pestaña Perfil, desplázate hacia abajo y toca "Cerrar Sesión". Tu sesión terminará inmediatamente y serás redirigido a la pantalla de inicio de sesión.',
    helpQ20: '¿Puedo editar mis publicaciones?',
    helpA20: '¡Sí! Toca el ícono de editar (lápiz) en tu publicación para editar el contenido.',
    helpQ21: '¿Mis datos están seguros?',
    helpA21: '¡Sí! Tu contraseña está encriptada y todas las comunicaciones API están seguras. Nunca compartimos tu información personal con terceros.',
    helpQ22: '¿Puedo usar la aplicación sin conexión?',
    helpA22: 'No, esta aplicación requiere una conexión a internet para cargar publicaciones, enviar mensajes y realizar todas las acciones.',
    helpQ23: '¿Quién puede ver mi perfil?',
    helpA23: 'Todos los usuarios registrados pueden ver tu perfil básico (nombre, nombre de usuario, foto de perfil, publicaciones). Solo los amigos pueden ver publicaciones marcadas como "Solo amigos".',
    
    // About
    aboutTitle: 'Acerca de Drivers Chat',
    aboutDescription: 'Drivers Chat es una plataforma comunitaria construida por conductores, para conductores. Conéctate con otros conductores de Uber y Lyft, comparte tus experiencias y construye conexiones significativas.',
    aboutVersion: 'Versión',
    aboutSupport: 'Soporte',
    aboutTerms: 'Términos y Condiciones',
    viewTerms: 'Ver Términos y Condiciones',
    
    // Terms Modal
    termsTitle: 'Términos y Condiciones',
    termsOfService: 'Términos de Servicio',
    communityGuidelines: 'Directrices de la Comunidad',
    termsAccept: 'Acepto',
    termsDecline: 'Rechazar',
    termsStep: 'Paso',
    termsOf: 'de',
    termsAgreeService: 'He leído y acepto los Términos de Servicio',
    termsAgreeGuidelines: 'He leído y acepto seguir las Directrices de la Comunidad',
    termsContinue: 'Continuar',
    termsAcceptStart: 'Aceptar & Empezar a Usar Drivers Chat',
    termsEffectiveDate: 'Fecha de Vigencia: Enero 2025',
    termsWelcome: '¡Bienvenido a Drivers Chat! Por favor lee estos términos cuidadosamente antes de usar nuestra aplicación.',
    termsNonCommercial: 'Aplicación No Comercial',
    termsLimitationLiability: 'Limitación de Responsabilidad',
    termsYourRights: 'Tus Derechos & Control de Cuenta',
    termsDataPrivacy: 'Datos & Privacidad',
    termsAgeRequirement: 'Requisito de Edad',
    termsAccountSecurity: 'Seguridad de la Cuenta',
    termsServiceChanges: 'Cambios de Servicio & Terminación',
    termsContact: 'Contacto',
    termsSupportEmail: 'support@drvchat.com',
    guidelinesKeepSafe: 'Mantén Drivers Chat Seguro & Respetuoso',
    guidelinesIntro: 'Estas directrices aseguran una experiencia positiva para todos los miembros. Las violaciones resultarán en suspensión de cuenta o prohibición permanente.',
    guidelinesProhibited: 'Contenido Estrictamente Prohibido',
    guidelinesConsequences: 'Consecuencias',
    guidelinesWhatYouCan: 'Lo Que PUEDES Compartir',
    guidelinesReport: 'Reportar Violaciones',
    
    // About page
    aboutWherDriversConnect: 'Donde los Conductores se Conectan',
    aboutTheApp: 'Acerca de la Aplicación',
    aboutAppDescription: 'Drivers Chat es una plataforma social GRATUITA construida exclusivamente para conductores de Uber y Lyft. Conéctate con otros conductores, comparte experiencias, obtén consejos y mantente informado sobre todo relacionado con conducir rideshare.',
    aboutOurMission: 'Nuestra Misión',
    aboutMissionDescription: 'Crear una comunidad de apoyo donde los conductores de rideshare puedan conectarse, compartir conocimientos y ayudarse mutuamente a navegar los desafíos y oportunidades de conducir para Uber y Lyft.',
    aboutKeyFeatures: 'Características Clave',
    aboutFeature1: 'Conecta con conductores a nivel nacional',
    aboutFeature2: 'Mensajería en tiempo real',
    aboutFeature3: 'Comparte consejos y experiencias',
    aboutFeature4: 'Moderación de contenido impulsada por la comunidad',
    aboutFeature5: 'Sistema de recompensas por referencia',
    aboutFeature6: 'Comunidad segura y respetuosa',
    aboutFree: '100% Gratis',
    aboutFreeDescription: 'Drivers Chat es completamente gratis sin membresías pagas, funciones premium o costos ocultos. Esta es una plataforma no comercial construida por conductores, para conductores.',
    aboutCommunityGuidelines: 'Directrices de la Comunidad',
    aboutGuidelinesDescription: 'Mantenemos un entorno seguro y respetuoso prohibiendo actividades comerciales, contenido político, apuestas, contenido para adultos, discurso de odio y actividades ilegales. Los usuarios que violen nuestras directrices enfrentan suspensión de cuenta o prohibiciones permanentes.',
    aboutReadFullTerms: 'Leer Términos & Directrices Completos →',
    aboutContactSupport: 'Contacto & Soporte',
    aboutContactDescription: '¿Tienes preguntas, comentarios o necesitas ayuda?',
    aboutEmailUs: 'Envíanos un correo a:',
    aboutVisitHelp: 'Visitar Centro de Ayuda →',
    aboutLegal: 'Legal',
    aboutTermsService: 'Términos de Servicio',
    aboutPrivacyPolicy: 'Política de Privacidad',
    aboutMadeWith: 'Hecho con ❤️ para conductores de rideshare',
    aboutCopyright: '© 2025 Drivers Chat. Todos los derechos reservados.',
    aboutLegalGuidelines: 'Legal & Directrices',
  },
};

export const useTranslation = () => {
  const language = useLanguageStore((state) => state.language);
  
  const t = (key: keyof typeof translations.en): string => {
    return translations[language][key] || translations.en[key] || key;
  };
  
  return { t, language };
};
