import { create } from 'zustand';
import AsyncStorage from '@react-native-async-storage/async-storage';

type Language = 'en' | 'tr' | 'es';

interface LanguageState {
  language: Language;
  setLanguage: (lang: Language) => Promise<void>;
  loadLanguage: () => Promise<void>;
}

export const useLanguageStore = create<LanguageState>((set) => ({
  language: 'en',
  
  setLanguage: async (lang: Language) => {
    try {
      await AsyncStorage.setItem('language', lang);
      set({ language: lang });
    } catch (error) {
      console.error('Error saving language:', error);
    }
  },
  
  loadLanguage: async () => {
    try {
      const savedLang = await AsyncStorage.getItem('language');
      if (savedLang) {
        set({ language: savedLang as Language });
      }
    } catch (error) {
      console.error('Error loading language:', error);
    }
  },
}));

// Translation strings
export const translations = {
  en: {
    // Auth
    login: 'Login',
    register: 'Sign Up',
    email: 'Email',
    password: 'Password',
    username: 'Username',
    fullName: 'Full Name',
    forgotPassword: 'Forgot Password?',
    dontHaveAccount: "Don't have an account? Sign up",
    alreadyHaveAccount: 'Already have an account? Sign in',
    aboutApp: 'About Drivers Chat',
    error: 'Error',
    success: 'Success',
    fillAllFields: 'Please fill in all fields',
    fillAllRequiredFields: 'Please fill in all required fields',
    selectLanguage: 'Select Language',
    passwordMinLength: 'Password must be at least 6 characters',
    passwordMinLengthPlaceholder: 'Password (min. 6 characters)',
    referralCodeOptional: 'Referral Code (optional)',
    creatingAccount: 'Creating account...',
    joinDriverCommunity: 'Join the driver community',
    confirmDriver: 'I work as a professional driver',
    mustConfirmDriver: 'Please confirm that you work as a professional driver',
    confirm18Plus: 'I confirm I am 18 years old or older',
    mustConfirm18Plus: 'You must be 18 years or older to use this app',
    
    // Tabs
    home: 'Home',
    messages: 'Messages',
    friends: 'Friends',
    profile: 'Profile',
    
    // Common
    post: 'Post',
    send: 'Send',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    settings: 'Settings',
    help: 'Help',
    about: 'About',
    signOut: 'Sign Out',
    loading: 'Loading...',
    
    // Posts
    createPost: 'Create Post',
    newPost: 'New Post',
    editPost: 'Edit Post',
    whatsOnYourMind: "What's on your mind?",
    publishing: 'Publishing...',
    addPhoto: 'Add Photo',
    noPostsYet: 'No posts yet',
    beFirstToPost: 'Be the first to post!',
    postPublished: 'Your post has been published',
    writeError: 'Please write something',
    failedCreatePost: 'Failed to create post',
    postUpdated: 'Post updated successfully',
    failedUpdatePost: 'Failed to update post',
    postDeleted: 'Post deleted successfully',
    failedDeletePost: 'Failed to delete post',
    postRemoved: 'This post was removed due to community feedback',
    
    // Privacy
    whoCanSee: 'Who can see this?',
    publicEveryone: 'Public - Everyone',
    friendsOnly: 'Friends - Only friends',
    specificFriends: 'Specific - Choose friends',
    noFriendsYet: 'No friends yet. Add friends to share with specific people.',
    
    // Delete confirmation
    deletePostTitle: 'Delete Post',
    deletePostMessage: 'Are you sure you want to delete your post?',
    deletePostAdminMessage: 'Are you sure you want to delete this post as an admin?',
    
    // Profile
    viewMyProfile: 'View My Profile',
    yourReferralCode: 'Your Referral Code',
    peopleJoined: 'people joined with your code',
    profilePictureUpdated: 'Profile picture updated successfully!',
    failedUpdatePicture: 'Failed to update profile picture',
    logoutError: 'Failed to sign out. Please try again.',
    
    // Settings
    accountSettings: 'Account Settings',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    updatePassword: 'Update Password',
    deleteAccount: 'Delete Account',
    deleteAccountWarning: 'This action cannot be undone. All your data will be permanently deleted.',
    deleteAccountConfirm: 'Delete My Account',
    language: 'Language',
    passwordUpdated: 'Password updated successfully',
    passwordsDontMatch: 'Passwords do not match',
    accountDeleted: 'Account deleted successfully',
    
    // Help
    helpTitle: 'Help & FAQ',
    helpQuestion1: 'What is Drivers Chat?',
    helpAnswer1: 'Drivers Chat is a social platform designed specifically for professional drivers to connect, share experiences, and communicate with each other.',
    helpQuestion2: 'How do I create a post?',
    helpAnswer2: 'Tap the + button on the home screen. You can write text, add photos, and choose who can see your post (Public, Friends, or Specific friends).',
    helpQuestion3: 'What are likes and dislikes?',
    helpAnswer3: 'You can like (👍) or dislike (👎) posts and comments. If a post gets 10 or more dislikes and dislikes exceed likes, it will be automatically removed.',
    helpQuestion4: 'How do I add friends?',
    helpAnswer4: 'Go to the Friends tab, search for users, and send them a friend request. Once accepted, you can share posts with them.',
    helpQuestion5: 'What is a referral code?',
    helpAnswer5: 'Your unique referral code can be shared with other drivers. When they sign up using your code, you both benefit from being connected!',
    helpQuestion6: 'How do I change my profile picture?',
    helpAnswer6: 'Go to Profile tab and tap on your profile picture to upload a new photo.',
    helpQuestion7: 'How do I contact support?',
    helpAnswer7: 'For support, email us at support@drvchat.com',
    helpHowCanWeHelp: 'How can we help you?',
    helpFindAnswers: 'Find answers to common questions about Drivers Chat',
    helpStillNeed: 'Still need help?',
    helpContactUs: 'Contact us at',
    
    // Help Categories
    helpCategoryAccount: 'Account & Profile',
    helpCategoryFriends: 'Friends System',
    helpCategoryPosts: 'Posts & Sharing',
    helpCategoryMessages: 'Messaging',
    helpCategoryOther: 'Other',
    
    // Help Q&A - Account
    helpQ1: 'How do I register?',
    helpA1: 'On the registration screen, enter your username, email, password, and full name. You can also enter a referral code if you have one. Click "Register" to create your account.',
    helpQ2: 'How do I change my profile picture?',
    helpA2: 'Go to the Profile tab, tap on your profile picture, and select a new photo from your gallery. The photo will be cropped to a square and uploaded automatically.',
    helpQ3: 'What is a referral code?',
    helpA3: 'A referral code is your unique code shown on your profile page. Share it with friends so they can enter it when registering. You\'ll see how many people joined using your code.',
    helpQ4: 'How do I reset my password?',
    helpA4: 'On the login screen, click "Forgot Password?", enter your email and username, and follow the instructions to reset your password.',
    
    // Help Q&A - Friends
    helpQ5: 'How do I add friends?',
    helpA5: 'Go to the Friends tab, use the search bar to find users by username or name, then tap "Add Friend" to send a friend request. You can also add a personal message.',
    helpQ6: 'How do I accept friend requests?',
    helpA6: 'Go to the Friends tab and check the "Friend Requests" section. You\'ll see a badge on the Friends tab icon if you have pending requests. Tap "Accept" or "Decline" for each request.',
    helpQ7: 'Can I remove friends?',
    helpA7: 'Currently, the friend removal feature is not available. This feature will be added in future updates.',
    helpQ8: 'Where can I see my friends list?',
    helpA8: 'Go to the Friends tab and scroll down to see your complete friends list with their profile pictures and names.',
    
    // Help Q&A - Posts
    helpQ9: 'How do I create a post?',
    helpA9: 'On the Home tab, tap the "+" icon in the top right. Write your content, optionally add a photo, choose privacy settings, and tap "Post".',
    helpQ10: 'What are privacy settings?',
    helpA10: 'When creating a post, you can choose:\n• Public: Everyone can see\n• Friends: Only your friends can see\n• Specific: Choose specific friends who can see the post',
    helpQ11: 'How does Like/Dislike work?',
    helpA11: 'You can like 👍 or dislike 👎 any post except your own. Tap the thumbs up to like, or thumbs down to dislike. You can change your vote anytime.',
    helpQ12: 'What happens if a post gets too many dislikes?',
    helpA12: 'If a post receives more than 10 total votes and more than 50% are dislikes, it will be automatically deleted to maintain content quality.',
    helpQ13: 'Can I vote on my own posts?',
    helpA13: 'No, you cannot like or dislike your own posts. The vote buttons will be disabled (grayed out) on your posts.',
    helpQ14: 'How do I view someone\'s profile?',
    helpA14: 'Tap on any username or profile picture in posts or the friends list to view their profile and see all their posts.',
    
    // Help Q&A - Messages
    helpQ15: 'How does the Chat Room work?',
    helpA15: 'Chat Room is a public space where all users can chat in real-time. Go to the Chat Room tab and start messaging. Everyone can see and participate!',
    helpQ16: 'Can I delete my chat messages?',
    helpA16: 'Yes! You can delete your own messages by tapping the trash icon on your message. Admins can also delete any message or clear the entire chat.',
    helpQ17: 'How do I create or join groups?',
    helpA17: 'Go to the Groups tab, tap the + button to create a group. You can join public groups directly or request to join private groups that require approval.',
    helpQ18: 'Can I share posts to groups?',
    helpA18: 'Yes! Group members can share posts with images and emojis to the group. All group posts support likes, dislikes, emoji reactions, and comments.',
    
    // Help Q&A - Other
    helpQ19: 'How do I sign out?',
    helpA19: 'Go to the Profile tab, scroll down, and tap "Sign Out". Your session will end immediately and you\'ll be redirected to the login screen.',
    helpQ20: 'Can I edit my posts?',
    helpA20: 'Yes! Tap the edit icon (pencil) on your post to edit the content.',
    helpQ21: 'Is my data secure?',
    helpA21: 'Yes! Your password is encrypted, and all API communications are secured. We never share your personal information with third parties.',
    helpQ22: 'Can I use the app offline?',
    helpA22: 'No, this app requires an internet connection to load posts, send messages, and perform all actions.',
    helpQ23: 'Who can see my profile?',
    helpA23: 'All registered users can view your basic profile (name, username, profile picture, posts). Only friends can see posts marked as "Friends only".',
    
    // Settings page
    settingsEditProfile: 'Edit Profile',
    settingsNameBio: 'Name, Bio',
    settingsSecurity: 'Security',
    settingsUpdatePassword: 'Update your password',
    settingsNotifications: 'Notifications',
    settingsFriendRequests: 'Friend Requests',
    settingsGetNotifiedRequests: 'Get notified of new requests',
    settingsGetNotifiedMessages: 'Get notified of new messages',
    settingsLikes: 'Likes',
    settingsGetNotifiedLikes: 'Get notified when someone likes your post',
    settingsGetNotifiedComments: 'Get notified of new comments on your posts',
    notificationsDisabledWarning: 'Push notifications are disabled. Enable them in device settings to receive alerts.',
    settingsGeneral: 'General',
    settingsDarkMode: 'Dark Mode',
    settingsComingSoon: 'Coming soon',
    settingsDangerZone: 'Danger Zone',
    settingsDeleteAccount: 'Delete Account',
    settingsPermanentlyDelete: 'Permanently delete your account',
    settingsProfile: 'Profile',
    settingsSaving: 'Saving...',
    settingsChanging: 'Changing...',
    settingsChange: 'Change',
    settingsEnterName: 'Enter your name',
    settingsBio: 'Bio',
    settingsTellAboutYourself: 'Tell us about yourself',
    settingsEmailReadOnly: 'Email (Read-only)',
    settingsEmailCannotChange: 'Email cannot be changed',
    settingsEnterCurrentPassword: 'Enter current password',
    settingsEnterNewPassword: 'Enter new password',
    settingsReenterNewPassword: 'Re-enter new password',
    settingsPasswordMinChars: 'Password must be at least 6 characters',
    settingsLanguageChanged: 'Language Changed',
    settingsLanguageSetTo: 'Language set to',
    settingsDeleteAccountQuestion: 'Delete Account?',
    settingsDeleteWarning: 'This action cannot be undone. All your posts, messages, and data will be permanently deleted.',
    settingsTypeDelete: 'Type',
    settingsToConfirm: 'to confirm:',
    settingsTypeDeleteHere: 'Type DELETE here',
    settingsDeleteForever: 'Delete Forever',
    settingsNameCannotEmpty: 'Name cannot be empty',
    settingsProfileUpdated: 'Profile updated successfully!',
    settingsFailedUpdateProfile: 'Failed to update profile',
    settingsNewPasswordsNoMatch: 'New passwords do not match',
    settingsFailedChangePassword: 'Failed to change password',
    settingsPasswordChanged: 'Password changed successfully!',
    settingsAccountDeleted: 'Your account has been permanently deleted',
    settingsFailedDeleteAccount: 'Failed to delete account',
    settingsPleaseTypeDelete: 'Please type DELETE to confirm',
    
    // Messages/Chat
    messagesNoMessagesYet: 'No messages yet',
    messagesStartChatting: 'Start chatting!',
    messagesNewChat: 'New Chat',
    
    // Friends
    friendsTitle: 'Friends',
    friendsSearchDrivers: 'Search drivers...',
    friendsFriendRequests: 'Friend Requests',
    friendsMyFriends: 'My Friends',
    friendsNoFriendsYet: 'No friends yet',
    friendsSearchAddFriends: 'Search and add friends above!',
    friendsFriendRequestSent: 'Friend request sent!',
    friendsFailedSendRequest: 'Failed to send request',
    friendsFriendAdded: 'Friend added!',
    friendsRequestRejected: 'Request rejected',
    friendsActionFailed: 'Action failed',
    
    // Forgot Password
    forgotPasswordTitle: 'Forgot Password',
    forgotPasswordInstruction: 'Enter your email and username to reset your password',
    forgotPasswordResetButton: 'Reset Password',
    forgotPasswordCheckEmail: 'Check Your Email',
    forgotPasswordEmailSent: 'Password reset instructions have been sent to your email.',
    forgotPasswordBackToLogin: 'Back to Login',
    forgotPasswordFailed: 'Failed to send reset email',
    
    // Post Detail
    postDetailComments: 'Comments',
    postDetailNoComments: 'No comments yet',
    postDetailBeFirst: 'Be the first to comment!',
    postDetailWriteComment: 'Write a comment...',
    postDetailSendComment: 'Send',
    postDetailCommentPosted: 'Comment posted!',
    postDetailFailedComment: 'Failed to post comment',
    
    // Profile Detail
    profileDetailSendMessage: 'Send Message',
    profileDetailAddFriend: 'Add Friend',
    profileDetailPosts: 'Posts',
    profileDetailNoPosts: 'No posts yet',
    
    // Referral Share
    shareReferralCode: 'Share Referral Code',
    nextStarIn: 'Next star in',
    referrals: 'referrals',
    
    // Edit Post Modal
    editPostSaveChanges: 'Save Changes',
    
    // Full Screen Image
    fullScreenImageClose: 'Close',
    
    // Search
    searchPosts: 'Search posts...',
    searchResults: 'Search Results',
    noResultsFound: 'No results found',
    searching: 'Searching...',
    
    // Comments
    comments: 'Comments',
    viewAllComments: 'View all comments',
    writeComment: 'Write a comment...',
    noComments: 'No comments yet',
    
    // Block User
    blockUser: 'Block User',
    unblockUser: 'Unblock User',
    blockedUsers: 'Blocked Users',
    blockUserConfirm: 'Are you sure you want to block this user? You won\'t see their posts or messages.',
    unblockUserConfirm: 'Are you sure you want to unblock this user?',
    userBlocked: 'User blocked successfully',
    userUnblocked: 'User unblocked successfully',
    noBlockedUsers: 'No blocked users',
    
    // Report System
    reportPost: 'Report Post',
    reportUser: 'Report User',
    reportComment: 'Report Comment',
    selectReason: 'Select a reason',
    spam: 'Spam',
    harassment: 'Harassment',
    inappropriate: 'Inappropriate Content',
    hateSpeech: 'Hate Speech',
    violence: 'Violence',
    other: 'Other',
    additionalDetails: 'Additional details (optional)',
    submitReport: 'Submit Report',
    reportSubmitted: 'Report submitted successfully',
    reportFailed: 'Failed to submit report',
    reports: 'Reports',
    pending: 'Pending',
    reviewed: 'Reviewed',
    resolved: 'Resolved',
    dismissed: 'Dismissed',
    
    // About
    aboutTitle: 'About Drivers Chat',
    aboutDescription: 'Drivers Chat is a community platform built by drivers, for drivers. Connect with fellow drivers, share your experiences, and build meaningful connections.',
    aboutVersion: 'Version',
    aboutSupport: 'Support',
    aboutTerms: 'Terms & Conditions',
    viewTerms: 'View Terms & Conditions',
    
    // Terms Modal
    termsTitle: 'Terms & Conditions',
    termsOfService: 'Terms of Service',
    communityGuidelines: 'Community Guidelines',
    termsAccept: 'I Accept',
    termsDecline: 'Decline',
    termsStep: 'Step',
    termsOf: 'of',
    termsAgreeService: 'I have read and agree to the Terms of Service',
    termsAgreeGuidelines: 'I have read and agree to follow the Community Guidelines',
    termsContinue: 'Continue',
    termsAcceptStart: 'Accept & Start Using Drivers Chat',
    termsEffectiveDate: 'Effective Date: January 2025',
    termsWelcome: 'Welcome to Drivers Chat! Please read these terms carefully before using our application.',
    termsNonCommercial: 'Non-Commercial Application',
    termsLimitationLiability: 'Limitation of Liability',
    termsYourRights: 'Your Rights & Account Control',
    termsDataPrivacy: 'Data & Privacy',
    termsAgeRequirement: 'Age Requirement',
    termsAccountSecurity: 'Account Security',
    termsServiceChanges: 'Service Changes & Termination',
    termsContact: 'Contact',
    termsSupportEmail: 'support@drvchat.com',
    guidelinesKeepSafe: 'Keep Drivers Chat Safe & Respectful',
    guidelinesIntro: 'These guidelines ensure a positive experience for all members. Violations will result in account suspension or permanent ban.',
    guidelinesProhibited: 'Strictly Prohibited Content',
    guidelinesConsequences: 'Consequences',
    guidelinesWhatYouCan: 'What You CAN Share',
    guidelinesReport: 'Report Violations',
    
    // About page
    aboutWherDriversConnect: 'Where Drivers Connect',
    aboutTheApp: 'About the App',
    aboutAppDescription: 'Drivers Chat is a FREE social platform built exclusively for professional drivers. Connect with fellow drivers, share experiences, get tips, and stay informed about everything related to driving.',
    aboutOurMission: 'Our Mission',
    aboutMissionDescription: 'To create a supportive community where drivers can connect, share knowledge, and help each other navigate the challenges and opportunities of professional driving.',
    aboutKeyFeatures: 'Key Features',
    aboutFeature1: 'Connect with drivers nationwide',
    aboutFeature2: 'Public chat room - Real-time conversations',
    aboutFeature3: 'Create and join driver groups',
    aboutFeature4: 'Share posts with photos and emoji reactions',
    aboutFeature5: 'Referral rewards system',
    aboutFeature6: 'Admin moderation and safe community',
    aboutFree: '100% Free',
    aboutFreeDescription: 'Drivers Chat is completely free with no paid memberships, premium features, or hidden costs. This is a non-commercial platform built by drivers, for drivers.',
    aboutCommunityGuidelines: 'Community Guidelines',
    aboutGuidelinesDescription: 'We maintain a safe and respectful environment by prohibiting commercial activities, political content, gambling, adult content, hate speech, and illegal activities. Users who violate our guidelines face account suspension or permanent bans.',
    aboutReadFullTerms: 'Read Full Terms & Guidelines →',
    aboutContactSupport: 'Contact & Support',
    aboutContactDescription: 'Have questions, feedback, or need help?',
    aboutEmailUs: 'Email us at:',
    aboutVisitHelp: 'Visit Help Center →',
    aboutLegal: 'Legal',
    aboutTermsService: 'Terms of Service',
    aboutPrivacyPolicy: 'Privacy Policy',
    aboutMadeWith: 'Made with ❤️ for drivers',
    aboutCopyright: '© 2025 Drivers Chat. All rights reserved.',
    aboutLegalGuidelines: 'Legal & Guidelines',
    
    // Admin Panel
    adminPanel: 'Admin Panel',
    adminStatistics: 'Statistics',
    adminReports: 'Reports',
    adminUsers: 'Users',
    adminPosts: 'Posts',
    adminTotalUsers: 'Total Users',
    adminTotalPosts: 'Total Posts',
    adminTotalComments: 'Total Comments',
    adminTotalReports: 'Total Reports',
    adminPendingReports: 'Pending Reports',
    adminRecentUsers: 'New Users (7d)',
    adminRecentPosts: 'New Posts (7d)',
    adminViewReports: 'View Reports',
    adminManageUsers: 'Manage Users',
    adminManagePosts: 'Manage Posts',
    adminReportedBy: 'Reported by',
    adminReportedUser: 'Reported User',
    adminReason: 'Reason',
    adminDescription: 'Description',
    adminStatus: 'Status',
    adminPending: 'Pending',
    adminReviewed: 'Reviewed',
    adminResolved: 'Resolved',
    adminDismissed: 'Dismissed',
    adminMarkReviewed: 'Mark Reviewed',
    adminMarkResolved: 'Mark Resolved',
    adminDismiss: 'Dismiss',
    adminNoReports: 'No reports found',
    adminUserList: 'User List',
    adminJoined: 'Joined',
    adminIsAdmin: 'Admin',
    adminMakeAdmin: 'Make Admin',
    adminRemoveAdmin: 'Remove Admin',
    adminBanUser: 'Ban User',
    adminUnbanUser: 'Unban User',
    adminNoUsers: 'No users found',
    adminPostList: 'Post List',
    adminPostedBy: 'Posted by',
    adminLikes: 'Likes',
    adminDislikes: 'Dislikes',
    adminComments: 'Comments',
    adminDeletePost: 'Delete Post',
    adminNoPosts: 'No posts found',
    adminConfirmDelete: 'Are you sure you want to delete this post?',
    adminConfirmBan: 'Are you sure you want to ban this user?',
    adminConfirmUnban: 'Are you sure you want to unban this user?',
    adminConfirmMakeAdmin: 'Are you sure you want to make this user an admin?',
    adminConfirmRemoveAdmin: 'Are you sure you want to remove admin rights from this user?',
    adminSuccess: 'Success',
    adminError: 'Error',
    adminSpam: 'Spam',
    adminHarassment: 'Harassment',
    adminInappropriate: 'Inappropriate Content',
    adminHateSpeech: 'Hate Speech',
    adminViolence: 'Violence',
    adminOther: 'Other',
    
    // Groups
    groups: 'Groups',
    myGroups: 'My Groups',
    discoverGroups: 'Discover Groups',
    createGroup: 'Create Group',
    groupName: 'Group Name',
    groupDescription: 'Group Description (optional)',
    groupPrivacy: 'Group Privacy',
    publicGroup: 'Public - Anyone can join',
    privateGroup: 'Private - Requires approval',
    members: 'Members',
    creator: 'Creator',
    joinGroup: 'Join Group',
    leaveGroup: 'Leave Group',
    deleteGroup: 'Delete Group',
    requestSent: 'Request Sent',
    joinRequests: 'Join Requests',
    approve: 'Approve',
    reject: 'Reject',
    noGroups: 'No groups found',
    noGroupsYet: "You haven't joined any groups yet",
    createFirstGroup: 'Create your first group',
    groupCreated: 'Group created successfully',
    groupDeleted: 'Group deleted successfully',
    leftGroup: 'Left group successfully',
    joinedGroup: 'Joined group successfully',
    requestApproved: 'Request approved',
    requestRejected: 'Request rejected',
    confirmDeleteGroup: 'Are you sure you want to delete this group? All posts will remain but will no longer be associated with the group.',
    confirmLeaveGroup: 'Are you sure you want to leave this group?',
    enterGroupName: 'Please enter a group name',
    postToGroup: 'Post to Group',
    groupPosts: 'Group Posts',
    noPostsInGroup: 'No posts in this group yet',
    shareToGroup: 'Share to this group',
    
    // Chat Room
    chatRoom: 'Chat Room',
    publicChat: 'Public Chat',
    everyoneCanSee: 'Everyone can see and send messages',
    typeMessage: 'Type a message...',
    send: 'Send',
    noChatMessages: 'No messages yet. Start the conversation!',
    justNow: 'Just now',
    online: 'online',
    deleteMessage: 'Delete Message',
    confirmDeleteMessage: 'Are you sure you want to delete this message?',
    clearChat: 'Clear Chat',
    confirmClearChat: 'Are you sure you want to delete all messages? This cannot be undone.',
    disableChat: 'Disable Chat',
    enableChat: 'Enable Chat',
    chatDisabled: 'Chat is disabled',
    chatDisabledMessage: 'The chat room has been disabled by admin',
  },
  tr: {
    // Auth
    login: 'Giriş Yap',
    register: 'Kayıt Ol',
    email: 'E-posta',
    password: 'Şifre',
    username: 'Kullanıcı Adı',
    fullName: 'Ad Soyad',
    forgotPassword: 'Şifremi Unuttum?',
    dontHaveAccount: 'Hesabınız yok mu? Kayıt olun',
    alreadyHaveAccount: 'Zaten hesabınız var mı? Giriş yapın',
    aboutApp: 'Drivers Chat Hakkında',
    error: 'Hata',
    success: 'Başarılı',
    fillAllFields: 'Lütfen tüm alanları doldurun',
    fillAllRequiredFields: 'Lütfen tüm gerekli alanları doldurun',
    selectLanguage: 'Dil Seçin',
    passwordMinLength: 'Şifre en az 6 karakter olmalıdır',
    passwordMinLengthPlaceholder: 'Şifre (min. 6 karakter)',
    referralCodeOptional: 'Referans Kodu (isteğe bağlı)',
    creatingAccount: 'Hesap oluşturuluyor...',
    joinDriverCommunity: 'Sürücü topluluğuna katılın',
    confirmDriver: 'Profesyonel şoför olarak çalışıyorum',
    mustConfirmDriver: 'Lütfen profesyonel şoför olarak çalıştığınızı onaylayın',
    confirm18Plus: '18 yaşında veya daha büyük olduğumu onaylıyorum',
    mustConfirm18Plus: 'Bu uygulamayı kullanmak için 18 yaşında veya daha büyük olmalısınız',
    
    // Tabs
    home: 'Ana Sayfa',
    messages: 'Mesajlar',
    friends: 'Arkadaşlar',
    profile: 'Profil',
    
    // Common
    post: 'Paylaş',
    send: 'Gönder',
    cancel: 'İptal',
    save: 'Kaydet',
    delete: 'Sil',
    edit: 'Düzenle',
    settings: 'Ayarlar',
    help: 'Yardım',
    about: 'Hakkında',
    signOut: 'Çıkış Yap',
    loading: 'Yükleniyor...',
    
    // Posts
    createPost: 'Gönderi Oluştur',
    newPost: 'Yeni Gönderi',
    editPost: 'Gönderiyi Düzenle',
    whatsOnYourMind: 'Ne düşünüyorsun?',
    publishing: 'Yayınlanıyor...',
    addPhoto: 'Fotoğraf Ekle',
    noPostsYet: 'Henüz gönderi yok',
    beFirstToPost: 'İlk paylaşan sen ol!',
    postPublished: 'Gönderiniz yayınlandı',
    writeError: 'Lütfen bir şeyler yazın',
    failedCreatePost: 'Gönderi oluşturulamadı',
    postUpdated: 'Gönderi başarıyla güncellendi',
    failedUpdatePost: 'Gönderi güncellenemedi',
    postDeleted: 'Gönderi başarıyla silindi',
    failedDeletePost: 'Gönderi silinemedi',
    postRemoved: 'Bu gönderi topluluk geri bildirimi nedeniyle kaldırıldı',
    
    // Privacy
    whoCanSee: 'Bunu kimler görebilir?',
    publicEveryone: 'Herkese Açık',
    friendsOnly: 'Arkadaşlar - Sadece arkadaşlar',
    specificFriends: 'Belirli Kişiler - Arkadaşları seç',
    noFriendsYet: 'Henüz arkadaş yok. Belirli kişilerle paylaşmak için arkadaş ekleyin.',
    
    // Delete confirmation
    deletePostTitle: 'Gönderiyi Sil',
    deletePostMessage: 'Gönderinizi silmek istediğinizden emin misiniz?',
    deletePostAdminMessage: 'Yönetici olarak bu gönderiyi silmek istediğinizden emin misiniz?',
    
    // Profile
    viewMyProfile: 'Profilimi Görüntüle',
    yourReferralCode: 'Referans Kodunuz',
    peopleJoined: 'kişi kodunuzla katıldı',
    profilePictureUpdated: 'Profil resmi başarıyla güncellendi!',
    failedUpdatePicture: 'Profil resmi güncellenemedi',
    logoutError: 'Çıkış yapılamadı. Lütfen tekrar deneyin.',
    
    // Settings
    accountSettings: 'Hesap Ayarları',
    changePassword: 'Şifre Değiştir',
    currentPassword: 'Mevcut Şifre',
    newPassword: 'Yeni Şifre',
    confirmPassword: 'Şifreyi Onayla',
    updatePassword: 'Şifreyi Güncelle',
    deleteAccount: 'Hesabı Sil',
    deleteAccountWarning: 'Bu işlem geri alınamaz. Tüm verileriniz kalıcı olarak silinecektir.',
    deleteAccountConfirm: 'Hesabımı Sil',
    language: 'Dil',
    passwordUpdated: 'Şifre başarıyla güncellendi',
    passwordsDontMatch: 'Şifreler eşleşmiyor',
    accountDeleted: 'Hesap başarıyla silindi',
    
    // Help
    helpTitle: 'Yardım & SSS',
    helpQuestion1: 'Drivers Chat nedir?',
    helpAnswer1: 'Drivers Chat, profesyonel sürücüler için özel olarak tasarlanmış bir sosyal platformdur. Sürücüler birbirleriyle bağlantı kurabilir, deneyimlerini paylaşabilir ve iletişim kurabilir.',
    helpQuestion2: 'Nasıl gönderi oluştururum?',
    helpAnswer2: 'Ana ekrandaki + butonuna dokunun. Metin yazabilir, fotoğraf ekleyebilir ve gönderinizi kimin görebileceğini seçebilirsiniz (Herkese Açık, Arkadaşlar veya Belirli arkadaşlar).',
    helpQuestion3: 'Beğeni ve beğenmeme nedir?',
    helpAnswer3: 'Gönderileri ve yorumları beğenebilir (👍) veya beğenmeyebilirsiniz (👎). Bir gönderi 10 veya daha fazla beğenmeme alırsa ve beğenmeme sayısı beğeni sayısını geçerse, otomatik olarak kaldırılır.',
    helpQuestion4: 'Nasıl arkadaş eklerim?',
    helpAnswer4: 'Arkadaşlar sekmesine gidin, kullanıcıları arayın ve arkadaşlık isteği gönderin. Kabul edildikten sonra onlarla gönderi paylaşabilirsiniz.',
    helpQuestion5: 'Referans kodu nedir?',
    helpAnswer5: 'Benzersiz referans kodunuzu diğer sürücülerle paylaşabilirsiniz. Kodunuzu kullanarak kayıt olduklarında, her ikiniz de bağlantılı olmaktan faydalanırsınız!',
    helpQuestion6: 'Profil resmimi nasıl değiştirebilirim?',
    helpAnswer6: 'Profil sekmesine gidin ve yeni bir fotoğraf yüklemek için profil resminize dokunun.',
    helpQuestion7: 'Desteğe nasıl ulaşabilirim?',
    helpAnswer7: 'Destek için bize support@drvchat.com adresinden e-posta gönderin',
    helpHowCanWeHelp: 'Nasıl yardımcı olabiliriz?',
    helpFindAnswers: 'Drivers Chat hakkında sık sorulan sorulara cevaplar bulun',
    helpStillNeed: 'Hala yardıma mı ihtiyacınız var?',
    helpContactUs: 'Bize ulaşın:',
    
    // Help Categories
    helpCategoryAccount: 'Hesap & Profil',
    helpCategoryFriends: 'Arkadaş Sistemi',
    helpCategoryPosts: 'Gönderiler & Paylaşım',
    helpCategoryMessages: 'Mesajlaşma',
    helpCategoryOther: 'Diğer',
    
    // Help Q&A - Account
    helpQ1: 'Nasıl kayıt olurum?',
    helpA1: 'Kayıt ekranında kullanıcı adınızı, e-postanızı, şifrenizi ve tam adınızı girin. Varsa bir referans kodu da girebilirsiniz. Hesabınızı oluşturmak için "Kayıt Ol"a tıklayın.',
    helpQ2: 'Profil resmimi nasıl değiştiririm?',
    helpA2: 'Profil sekmesine gidin, profil resminize dokunun ve galerinizden yeni bir fotoğraf seçin. Fotoğraf kareye kırpılacak ve otomatik olarak yüklenecektir.',
    helpQ3: 'Referans kodu nedir?',
    helpA3: 'Referans kodu, profil sayfanızda gösterilen benzersiz kodunuzdur. Arkadaşlarınızla paylaşın, böylece kayıt olurken girebilirler. Kodunuzla kaç kişinin katıldığını göreceksiniz.',
    helpQ4: 'Şifremi nasıl sıfırlarım?',
    helpA4: 'Giriş ekranında "Şifremi Unuttum?"a tıklayın, e-postanızı ve kullanıcı adınızı girin ve şifrenizi sıfırlamak için talimatları izleyin.',
    
    // Help Q&A - Friends
    helpQ5: 'Nasıl arkadaş eklerim?',
    helpA5: 'Arkadaşlar sekmesine gidin, kullanıcı adı veya ada göre kullanıcıları bulmak için arama çubuğunu kullanın, ardından arkadaşlık isteği göndermek için "Arkadaş Ekle"ye dokunun. Kişisel bir mesaj da ekleyebilirsiniz.',
    helpQ6: 'Arkadaşlık isteklerini nasıl kabul ederim?',
    helpA6: 'Arkadaşlar sekmesine gidin ve "Arkadaşlık İstekleri" bölümünü kontrol edin. Bekleyen istekleriniz varsa Arkadaşlar sekmesi simgesinde bir rozet göreceksiniz. Her istek için "Kabul Et" veya "Reddet"e dokunun.',
    helpQ7: 'Arkadaşları kaldırabilir miyim?',
    helpA7: 'Şu anda arkadaş kaldırma özelliği mevcut değil. Bu özellik gelecek güncellemelerde eklenecektir.',
    helpQ8: 'Arkadaş listemi nerede görebilirim?',
    helpA8: 'Arkadaşlar sekmesine gidin ve profil resimleri ve isimleri ile tüm arkadaş listenizi görmek için aşağı kaydırın.',
    
    // Help Q&A - Posts
    helpQ9: 'Nasıl gönderi oluştururum?',
    helpA9: 'Ana Sayfa sekmesinde sağ üstteki "+" simgesine dokunun. İçeriğinizi yazın, isteğe bağlı olarak bir fotoğraf ekleyin, gizlilik ayarlarını seçin ve "Paylaş"a dokunun.',
    helpQ10: 'Gizlilik ayarları nedir?',
    helpA10: 'Gönderi oluştururken şunları seçebilirsiniz:\n• Herkese Açık: Herkes görebilir\n• Arkadaşlar: Sadece arkadaşlarınız görebilir\n• Belirli: Gönderiyi görebilecek belirli arkadaşları seçin',
    helpQ11: 'Beğeni/Beğenmeme nasıl çalışır?',
    helpA11: 'Kendinizinkiler hariç herhangi bir gönderiyi beğenebilir 👍 veya beğenmeyebilirsiniz 👎. Beğenmek için başparmak yukarı, beğenmemek için başparmak aşağıya dokunun. Oyunuzu istediğiniz zaman değiştirebilirsiniz.',
    helpQ12: 'Bir gönderi çok fazla beğenmeme alırsa ne olur?',
    helpA12: '10\'dan fazla toplam oy alan ve %50\'den fazlası beğenmeme olan bir gönderi, içerik kalitesini korumak için otomatik olarak silinir.',
    helpQ13: 'Kendi gönderilerime oy verebilir miyim?',
    helpA13: 'Hayır, kendi gönderilerinizi beğenemez veya beğenmeyemezsiniz. Oy butonları gönderilerinizde devre dışı (gri) olacaktır.',
    helpQ14: 'Birinin profilini nasıl görüntülerim?',
    helpA14: 'Gönderilerdeki veya arkadaş listesindeki herhangi bir kullanıcı adına veya profil resmine dokunarak profillerini görüntüleyin ve tüm gönderilerini görün.',
    
    // Help Q&A - Messages
    helpQ15: 'Sohbet Odası nasıl çalışır?',
    helpA15: 'Sohbet Odası, tüm kullanıcıların gerçek zamanlı sohbet edebileceği herkese açık bir alandır. Sohbet Odası sekmesine gidin ve mesajlaşmaya başlayın. Herkes görebilir ve katılabilir!',
    helpQ16: 'Sohbet mesajlarımı silebilir miyim?',
    helpA16: 'Evet! Mesajınızdaki çöp kutusu simgesine dokunarak kendi mesajlarınızı silebilirsiniz. Adminler de herhangi bir mesajı silebilir veya tüm sohbeti temizleyebilir.',
    helpQ17: 'Nasıl grup oluştururum veya katılırım?',
    helpA17: 'Gruplar sekmesine gidin, grup oluşturmak için + butonuna dokunun. Herkese açık gruplara doğrudan katılabilir veya onay gerektiren özel gruplara katılma isteği gönderebilirsiniz.',
    helpQ18: 'Gruplara gönderi paylaşabilir miyim?',
    helpA18: 'Evet! Grup üyeleri gruba resim ve emoji içeren gönderiler paylaşabilir. Tüm grup gönderileri beğeni, beğenmeme, emoji tepkileri ve yorumları destekler.',
    
    // Help Q&A - Other
    helpQ19: 'Nasıl çıkış yaparım?',
    helpA19: 'Profil sekmesine gidin, aşağı kaydırın ve "Çıkış Yap"a dokunun. Oturumunuz hemen sona erecek ve giriş ekranına yönlendirileceksiniz.',
    helpQ20: 'Gönderilerimi düzenleyebilir miyim?',
    helpA20: 'Evet! İçeriği düzenlemek için gönderinizdeki düzenle simgesine (kalem) dokunun.',
    helpQ21: 'Verilerim güvende mi?',
    helpA21: 'Evet! Şifreniz şifrelenir ve tüm API iletişimleri güvenlidir. Kişisel bilgilerinizi asla üçüncü taraflarla paylaşmayız.',
    helpQ22: 'Uygulamayı çevrimdışı kullanabilir miyim?',
    helpA22: 'Hayır, bu uygulama gönderileri yüklemek, mesaj göndermek ve tüm işlemleri gerçekleştirmek için internet bağlantısı gerektirir.',
    helpQ23: 'Profilimi kimler görebilir?',
    helpA23: 'Tüm kayıtlı kullanıcılar temel profilinizi (ad, kullanıcı adı, profil resmi, gönderiler) görüntüleyebilir. Sadece arkadaşlar "Sadece arkadaşlar" olarak işaretlenmiş gönderileri görebilir.',
    
    // Settings page
    settingsEditProfile: 'Profili Düzenle',
    settingsNameBio: 'Ad, Bio',
    settingsSecurity: 'Güvenlik',
    settingsUpdatePassword: 'Şifrenizi güncelleyin',
    settingsNotifications: 'Bildirimler',
    settingsFriendRequests: 'Arkadaşlık İstekleri',
    settingsGetNotifiedRequests: 'Yeni istekler için bildirim al',
    settingsGetNotifiedMessages: 'Yeni mesajlar için bildirim al',
    settingsLikes: 'Beğeniler',
    settingsGetNotifiedLikes: 'Birisi gönderinizi beğendiğinde bildirim al',
    settingsGetNotifiedComments: 'Gönderilerinize yeni yorumlar geldiğinde bildirim al',
    notificationsDisabledWarning: 'Push bildirimleri kapalı. Uyarılar almak için cihaz ayarlarınızdan etkinleştirin.',
    settingsGeneral: 'Genel',
    settingsDarkMode: 'Karanlık Mod',
    settingsComingSoon: 'Yakında',
    settingsDangerZone: 'Tehlikeli Bölge',
    settingsDeleteAccount: 'Hesabı Sil',
    settingsPermanentlyDelete: 'Hesabınızı kalıcı olarak silin',
    settingsProfile: 'Profil',
    settingsSaving: 'Kaydediliyor...',
    settingsChanging: 'Değiştiriliyor...',
    settingsChange: 'Değiştir',
    settingsEnterName: 'Adınızı girin',
    settingsBio: 'Bio',
    settingsTellAboutYourself: 'Kendinizden bahsedin',
    settingsEmailReadOnly: 'E-posta (Salt okunur)',
    settingsEmailCannotChange: 'E-posta değiştirilemez',
    settingsEnterCurrentPassword: 'Mevcut şifrenizi girin',
    settingsEnterNewPassword: 'Yeni şifrenizi girin',
    settingsReenterNewPassword: 'Yeni şifrenizi tekrar girin',
    settingsPasswordMinChars: 'Şifre en az 6 karakter olmalıdır',
    settingsLanguageChanged: 'Dil Değiştirildi',
    settingsLanguageSetTo: 'Dil ayarlandı:',
    settingsDeleteAccountQuestion: 'Hesap Silinsin mi?',
    settingsDeleteWarning: 'Bu işlem geri alınamaz. Tüm gönderileriniz, mesajlarınız ve verileriniz kalıcı olarak silinecektir.',
    settingsTypeDelete: 'Yazın',
    settingsToConfirm: 'onaylamak için:',
    settingsTypeDeleteHere: 'Buraya DELETE yazın',
    settingsDeleteForever: 'Kalıcı Olarak Sil',
    settingsNameCannotEmpty: 'Ad boş olamaz',
    settingsProfileUpdated: 'Profil başarıyla güncellendi!',
    settingsFailedUpdateProfile: 'Profil güncellenemedi',
    settingsNewPasswordsNoMatch: 'Yeni şifreler eşleşmiyor',
    settingsFailedChangePassword: 'Şifre değiştirilemedi',
    settingsPasswordChanged: 'Şifre başarıyla değiştirildi!',
    settingsAccountDeleted: 'Hesabınız kalıcı olarak silindi',
    settingsFailedDeleteAccount: 'Hesap silinemedi',
    settingsPleaseTypeDelete: 'Lütfen onaylamak için DELETE yazın',
    
    // Messages/Chat
    messagesNoMessagesYet: 'Henüz mesaj yok',
    messagesStartChatting: 'Sohbete başlayın!',
    messagesNewChat: 'Yeni Sohbet',
    
    // Friends
    friendsTitle: 'Arkadaşlar',
    friendsSearchDrivers: 'Sürücü ara...',
    friendsFriendRequests: 'Arkadaşlık İstekleri',
    friendsMyFriends: 'Arkadaşlarım',
    friendsNoFriendsYet: 'Henüz arkadaş yok',
    friendsSearchAddFriends: 'Yukarıdan arkadaş arayın ve ekleyin!',
    friendsFriendRequestSent: 'Arkadaşlık isteği gönderildi!',
    friendsFailedSendRequest: 'İstek gönderilemedi',
    friendsFriendAdded: 'Arkadaş eklendi!',
    friendsRequestRejected: 'İstek reddedildi',
    friendsActionFailed: 'İşlem başarısız',
    
    // Forgot Password
    forgotPasswordTitle: 'Şifremi Unuttum',
    forgotPasswordInstruction: 'Şifrenizi sıfırlamak için e-posta ve kullanıcı adınızı girin',
    forgotPasswordResetButton: 'Şifreyi Sıfırla',
    forgotPasswordCheckEmail: 'E-postanızı Kontrol Edin',
    forgotPasswordEmailSent: 'Şifre sıfırlama talimatları e-postanıza gönderildi.',
    forgotPasswordBackToLogin: 'Girişe Dön',
    forgotPasswordFailed: 'Sıfırlama e-postası gönderilemedi',
    
    // Post Detail
    postDetailComments: 'Yorumlar',
    postDetailNoComments: 'Henüz yorum yok',
    postDetailBeFirst: 'İlk yorumu sen yap!',
    postDetailWriteComment: 'Yorum yaz...',
    postDetailSendComment: 'Gönder',
    postDetailCommentPosted: 'Yorum gönderildi!',
    postDetailFailedComment: 'Yorum gönderilemedi',
    
    // Profile Detail
    profileDetailSendMessage: 'Mesaj Gönder',
    profileDetailAddFriend: 'Arkadaş Ekle',
    profileDetailPosts: 'Gönderiler',
    profileDetailNoPosts: 'Henüz gönderi yok',
    
    // Referral Share
    shareReferralCode: 'Referans Kodunu Paylaş',
    nextStarIn: 'Sonraki yıldız',
    referrals: 'referanslar',
    
    // Edit Post Modal
    editPostSaveChanges: 'Değişiklikleri Kaydet',
    
    // Full Screen Image
    fullScreenImageClose: 'Kapat',
    
    // Search
    searchPosts: 'Gönderi ara...',
    searchResults: 'Arama Sonuçları',
    noResultsFound: 'Sonuç bulunamadı',
    searching: 'Aranıyor...',
    
    // Comments
    comments: 'Yorumlar',
    viewAllComments: 'Tüm yorumları gör',
    writeComment: 'Yorum yaz...',
    noComments: 'Henüz yorum yok',
    
    // Block User
    blockUser: 'Kullanıcıyı Engelle',
    unblockUser: 'Engeli Kaldır',
    blockedUsers: 'Engellenen Kullanıcılar',
    blockUserConfirm: 'Bu kullanıcıyı engellemek istediğinizden emin misiniz? Gönderilerini ve mesajlarını göremeyeceksiniz.',
    unblockUserConfirm: 'Bu kullanıcının engelini kaldırmak istediğinizden emin misiniz?',
    userBlocked: 'Kullanıcı başarıyla engellendi',
    userUnblocked: 'Kullanıcının engeli başarıyla kaldırıldı',
    noBlockedUsers: 'Engellenen kullanıcı yok',
    
    // Report System
    reportPost: 'Gönderiyi Bildir',
    reportUser: 'Kullanıcıyı Bildir',
    reportComment: 'Yorumu Bildir',
    selectReason: 'Bir sebep seçin',
    spam: 'Spam',
    harassment: 'Taciz',
    inappropriate: 'Uygunsuz İçerik',
    hateSpeech: 'Nefret Söylemi',
    violence: 'Şiddet',
    other: 'Diğer',
    additionalDetails: 'Ek detaylar (isteğe bağlı)',
    submitReport: 'Bildirimi Gönder',
    reportSubmitted: 'Bildirim başarıyla gönderildi',
    reportFailed: 'Bildirim gönderilemedi',
    reports: 'Bildirimler',
    pending: 'Beklemede',
    reviewed: 'İncelendi',
    resolved: 'Çözüldü',
    dismissed: 'Reddedildi',
    
    // About
    aboutTitle: 'Drivers Chat Hakkında',
    aboutDescription: 'Drivers Chat, sürücüler tarafından sürücüler için oluşturulmuş bir topluluk platformudur. Diğer profesyonel sürücülerle bağlantı kurun, deneyimlerinizi paylaşın ve anlamlı bağlantılar oluşturun.',
    aboutVersion: 'Versiyon',
    aboutSupport: 'Destek',
    aboutTerms: 'Şartlar & Koşullar',
    viewTerms: 'Şartlar & Koşulları Görüntüle',
    
    // Terms Modal
    termsTitle: 'Şartlar & Koşullar',
    termsOfService: 'Hizmet Şartları',
    communityGuidelines: 'Topluluk Kuralları',
    termsAccept: 'Kabul Ediyorum',
    termsDecline: 'Reddet',
    termsStep: 'Adım',
    termsOf: '/  ',
    termsAgreeService: 'Hizmet Şartlarını okudum ve kabul ediyorum',
    termsAgreeGuidelines: 'Topluluk Kurallarını okudum ve uyacağımı kabul ediyorum',
    termsContinue: 'Devam Et',
    termsAcceptStart: 'Kabul Et & Drivers Chat Kullanmaya Başla',
    termsEffectiveDate: 'Yürürlük Tarihi: Ocak 2025',
    termsWelcome: 'Drivers Chat\'e hoş geldiniz! Uygulamamızı kullanmadan önce lütfen bu şartları dikkatle okuyun.',
    termsNonCommercial: 'Ticari Olmayan Uygulama',
    termsLimitationLiability: 'Sorumluluk Sınırlaması',
    termsYourRights: 'Haklarınız & Hesap Kontrolü',
    termsDataPrivacy: 'Veri & Gizlilik',
    termsAgeRequirement: 'Yaş Gereksinimi',
    termsAccountSecurity: 'Hesap Güvenliği',
    termsServiceChanges: 'Hizmet Değişiklikleri & Sonlandırma',
    termsContact: 'İletişim',
    termsSupportEmail: 'support@drvchat.com',
    guidelinesKeepSafe: 'Drivers Chat\'i Güvenli & Saygılı Tutun',
    guidelinesIntro: 'Bu kurallar tüm üyeler için olumlu bir deneyim sağlar. İhlaller hesap askıya alınması veya kalıcı yasakla sonuçlanır.',
    guidelinesProhibited: 'Kesinlikle Yasak İçerik',
    guidelinesConsequences: 'Sonuçlar',
    guidelinesWhatYouCan: 'Paylaşabilecekleriniz',
    guidelinesReport: 'İhlalleri Bildirin',
    
    // About page
    aboutWherDriversConnect: 'Sürücülerin Buluştuğu Yer',
    aboutTheApp: 'Uygulama Hakkında',
    aboutAppDescription: 'Drivers Chat, profesyonel sürücüler için özel olarak oluşturulmuş ÜCRETSİZ bir sosyal platformdur. Diğer sürücülerle bağlantı kurun, deneyimleri paylaşın, ipuçları alın ve sürücülükle ilgili her şeyden haberdar olun.',
    aboutOurMission: 'Misyonumuz',
    aboutMissionDescription: 'Sürücülerin bağlantı kurabilecekleri, bilgi paylaşabilecekleri ve profesyonel sürücülüğün zorlukları ve fırsatlarında birbirlerine yardımcı olabilecekleri destekleyici bir topluluk oluşturmak.',
    aboutKeyFeatures: 'Temel Özellikler',
    aboutFeature1: 'Ülke çapında sürücülerle bağlantı kurun',
    aboutFeature2: 'Genel sohbet odası - Canlı konuşmalar',
    aboutFeature3: 'Sürücü grupları oluşturun ve katılın',
    aboutFeature4: 'Fotoğraf ve emoji ile gönderi paylaşın',
    aboutFeature5: 'Referans ödül sistemi',
    aboutFeature6: 'Admin moderasyonu ve güvenli topluluk',
    aboutFree: '100% Ücretsiz',
    aboutFreeDescription: 'Drivers Chat, ücretli üyelikler, premium özellikler veya gizli maliyetler olmadan tamamen ücretsizdir. Bu, sürücüler tarafından sürücüler için oluşturulmuş ticari olmayan bir platformdur.',
    aboutCommunityGuidelines: 'Topluluk Kuralları',
    aboutGuidelinesDescription: 'Ticari faaliyetleri, siyasi içeriği, kumar, yetişkinlere yönelik içerik, nefret söylemi ve yasadışı faaliyetleri yasaklayarak güvenli ve saygılı bir ortam sağlıyoruz. Kurallarımızı ihlal eden kullanıcılar hesap askıya alınması veya kalıcı yasaklarla karşı karşıya kalır.',
    aboutReadFullTerms: 'Tam Şartlar & Kuralları Okuyun →',
    aboutContactSupport: 'İletişim & Destek',
    aboutContactDescription: 'Sorularınız, geri bildiriminiz veya yardıma mı ihtiyacınız var?',
    aboutEmailUs: 'Bize e-posta gönderin:',
    aboutVisitHelp: 'Yardım Merkezini Ziyaret Edin →',
    aboutLegal: 'Yasal',
    aboutTermsService: 'Hizmet Şartları',
    aboutPrivacyPolicy: 'Gizlilik Politikası',
    aboutMadeWith: 'Sürücüler için ❤️ ile yapıldı',
    aboutCopyright: '© 2025 Drivers Chat. Tüm hakları saklıdır.',
    aboutLegalGuidelines: 'Yasal & Kurallar',
    
    // Admin Panel
    adminPanel: 'Yönetici Paneli',
    adminStatistics: 'İstatistikler',
    adminReports: 'Bildirimler',
    adminUsers: 'Kullanıcılar',
    adminPosts: 'Gönderiler',
    adminTotalUsers: 'Toplam Kullanıcı',
    adminTotalPosts: 'Toplam Gönderi',
    adminTotalComments: 'Toplam Yorum',
    adminTotalReports: 'Toplam Bildirim',
    adminPendingReports: 'Bekleyen Bildirimler',
    adminRecentUsers: 'Yeni Kullanıcılar (7g)',
    adminRecentPosts: 'Yeni Gönderiler (7g)',
    adminViewReports: 'Bildirimleri Görüntüle',
    adminManageUsers: 'Kullanıcıları Yönet',
    adminManagePosts: 'Gönderileri Yönet',
    adminReportedBy: 'Bildiren',
    adminReportedUser: 'Bildirilen Kullanıcı',
    adminReason: 'Sebep',
    adminDescription: 'Açıklama',
    adminStatus: 'Durum',
    adminPending: 'Beklemede',
    adminReviewed: 'İncelendi',
    adminResolved: 'Çözüldü',
    adminDismissed: 'Reddedildi',
    adminMarkReviewed: 'İncelendi Olarak İşaretle',
    adminMarkResolved: 'Çözüldü Olarak İşaretle',
    adminDismiss: 'Reddet',
    adminNoReports: 'Bildirim bulunamadı',
    adminUserList: 'Kullanıcı Listesi',
    adminJoined: 'Katılma',
    adminIsAdmin: 'Admin',
    adminMakeAdmin: 'Admin Yap',
    adminRemoveAdmin: 'Admin Kaldır',
    adminBanUser: 'Kullanıcıyı Yasakla',
    adminUnbanUser: 'Yasağı Kaldır',
    adminNoUsers: 'Kullanıcı bulunamadı',
    adminPostList: 'Gönderi Listesi',
    adminPostedBy: 'Gönderen',
    adminLikes: 'Beğeniler',
    adminDislikes: 'Beğenmemeler',
    adminComments: 'Yorumlar',
    adminDeletePost: 'Gönderiyi Sil',
    adminNoPosts: 'Gönderi bulunamadı',
    adminConfirmDelete: 'Bu gönderiyi silmek istediğinizden emin misiniz?',
    adminConfirmBan: 'Bu kullanıcıyı yasaklamak istediğinizden emin misiniz?',
    adminConfirmUnban: 'Bu kullanıcının yasağını kaldırmak istediğinizden emin misiniz?',
    adminConfirmMakeAdmin: 'Bu kullanıcıyı admin yapmak istediğinizden emin misiniz?',
    adminConfirmRemoveAdmin: 'Bu kullanıcının admin haklarını kaldırmak istediğinizden emin misiniz?',
    adminSuccess: 'Başarılı',
    adminError: 'Hata',
    adminSpam: 'Spam',
    adminHarassment: 'Taciz',
    adminInappropriate: 'Uygunsuz İçerik',
    adminHateSpeech: 'Nefret Söylemi',
    adminViolence: 'Şiddet',
    adminOther: 'Diğer',
    
    // Groups
    groups: 'Gruplar',
    myGroups: 'Gruplarım',
    discoverGroups: 'Grupları Keşfet',
    createGroup: 'Grup Oluştur',
    groupName: 'Grup Adı',
    groupDescription: 'Grup Açıklaması (opsiyonel)',
    groupPrivacy: 'Grup Gizliliği',
    publicGroup: 'Herkese Açık - Herkes katılabilir',
    privateGroup: 'Özel - Onay gerektirir',
    members: 'Üyeler',
    creator: 'Kurucu',
    joinGroup: 'Gruba Katıl',
    leaveGroup: 'Gruptan Ayrıl',
    deleteGroup: 'Grubu Sil',
    requestSent: 'İstek Gönderildi',
    joinRequests: 'Katılma İstekleri',
    approve: 'Onayla',
    reject: 'Reddet',
    noGroups: 'Grup bulunamadı',
    noGroupsYet: 'Henüz hiç gruba katılmadınız',
    createFirstGroup: 'İlk grubunuzu oluşturun',
    groupCreated: 'Grup başarıyla oluşturuldu',
    groupDeleted: 'Grup başarıyla silindi',
    leftGroup: 'Gruptan başarıyla ayrıldınız',
    joinedGroup: 'Gruba başarıyla katıldınız',
    requestApproved: 'İstek onaylandı',
    requestRejected: 'İstek reddedildi',
    confirmDeleteGroup: 'Bu grubu silmek istediğinizden emin misiniz? Tüm gönderiler kalacak ancak artık grupla ilişkilendirilmeyecek.',
    confirmLeaveGroup: 'Bu gruptan ayrılmak istediğinizden emin misiniz?',
    enterGroupName: 'Lütfen bir grup adı girin',
    postToGroup: 'Gruba Gönderi Paylaş',
    groupPosts: 'Grup Gönderileri',
    noPostsInGroup: 'Bu grupta henüz gönderi yok',
    shareToGroup: 'Bu gruba paylaş',
    
    // Chat Room
    chatRoom: 'Sohbet Odası',
    publicChat: 'Genel Sohbet',
    everyoneCanSee: 'Herkes mesajları görebilir ve gönderebilir',
    typeMessage: 'Bir mesaj yazın...',
    send: 'Gönder',
    noChatMessages: 'Henüz mesaj yok. Konuşmayı başlat!',
    justNow: 'Az önce',
    online: 'çevrimiçi',
    deleteMessage: 'Mesajı Sil',
    confirmDeleteMessage: 'Bu mesajı silmek istediğinizden emin misiniz?',
    clearChat: 'Tüm Sohbeti Temizle',
    confirmClearChat: 'Tüm mesajları silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.',
    disableChat: 'Sohbeti Kapat',
    enableChat: 'Sohbeti Aç',
    chatDisabled: 'Sohbet kapalı',
    chatDisabledMessage: 'Sohbet odası admin tarafından kapatılmıştır',
  },
  es: {
    // Auth
    login: 'Iniciar Sesión',
    register: 'Registrarse',
    email: 'Correo Electrónico',
    password: 'Contraseña',
    username: 'Nombre de Usuario',
    fullName: 'Nombre Completo',
    forgotPassword: '¿Olvidaste tu contraseña?',
    dontHaveAccount: '¿No tienes cuenta? Regístrate',
    alreadyHaveAccount: '¿Ya tienes cuenta? Inicia sesión',
    aboutApp: 'Acerca de Drivers Chat',
    error: 'Error',
    success: 'Éxito',
    fillAllFields: 'Por favor completa todos los campos',
    fillAllRequiredFields: 'Por favor completa todos los campos requeridos',
    selectLanguage: 'Seleccionar Idioma',
    passwordMinLength: 'La contraseña debe tener al menos 6 caracteres',
    passwordMinLengthPlaceholder: 'Contraseña (mín. 6 caracteres)',
    referralCodeOptional: 'Código de Referencia (opcional)',
    creatingAccount: 'Creando cuenta...',
    joinDriverCommunity: 'Únete a la comunidad de conductores',
    confirmDriver: 'Trabajo como conductor profesional',
    mustConfirmDriver: 'Por favor confirme que trabaja como conductor profesional',
    confirm18Plus: 'Confirmo que tengo 18 años o más',
    mustConfirm18Plus: 'Debes tener 18 años o más para usar esta aplicación',
    
    // Tabs
    home: 'Inicio',
    messages: 'Mensajes',
    friends: 'Amigos',
    profile: 'Perfil',
    
    // Common
    post: 'Publicar',
    send: 'Enviar',
    cancel: 'Cancelar',
    save: 'Guardar',
    delete: 'Eliminar',
    edit: 'Editar',
    settings: 'Configuración',
    help: 'Ayuda',
    about: 'Acerca de',
    signOut: 'Cerrar Sesión',
    loading: 'Cargando...',
    
    // Posts
    createPost: 'Crear Publicación',
    newPost: 'Nueva Publicación',
    editPost: 'Editar Publicación',
    whatsOnYourMind: '¿Qué estás pensando?',
    publishing: 'Publicando...',
    addPhoto: 'Agregar Foto',
    noPostsYet: 'Aún no hay publicaciones',
    beFirstToPost: '¡Sé el primero en publicar!',
    postPublished: 'Tu publicación ha sido publicada',
    writeError: 'Por favor escribe algo',
    failedCreatePost: 'Error al crear publicación',
    postUpdated: 'Publicación actualizada exitosamente',
    failedUpdatePost: 'Error al actualizar publicación',
    postDeleted: 'Publicación eliminada exitosamente',
    failedDeletePost: 'Error al eliminar publicación',
    postRemoved: 'Esta publicación fue eliminada debido a comentarios de la comunidad',
    
    // Privacy
    whoCanSee: '¿Quién puede ver esto?',
    publicEveryone: 'Público - Todos',
    friendsOnly: 'Amigos - Solo amigos',
    specificFriends: 'Específico - Elegir amigos',
    noFriendsYet: 'Aún no tienes amigos. Agrega amigos para compartir con personas específicas.',
    
    // Delete confirmation
    deletePostTitle: 'Eliminar Publicación',
    deletePostMessage: '¿Estás seguro de que quieres eliminar tu publicación?',
    deletePostAdminMessage: '¿Estás seguro de que quieres eliminar esta publicación como administrador?',
    
    // Profile
    viewMyProfile: 'Ver Mi Perfil',
    yourReferralCode: 'Tu Código de Referencia',
    peopleJoined: 'personas se unieron con tu código',
    profilePictureUpdated: '¡Foto de perfil actualizada exitosamente!',
    failedUpdatePicture: 'Error al actualizar foto de perfil',
    logoutError: 'Error al cerrar sesión. Por favor intenta de nuevo.',
    
    // Settings
    accountSettings: 'Configuración de Cuenta',
    changePassword: 'Cambiar Contraseña',
    currentPassword: 'Contraseña Actual',
    newPassword: 'Nueva Contraseña',
    confirmPassword: 'Confirmar Contraseña',
    updatePassword: 'Actualizar Contraseña',
    deleteAccount: 'Eliminar Cuenta',
    deleteAccountWarning: 'Esta acción no se puede deshacer. Todos tus datos serán eliminados permanentemente.',
    deleteAccountConfirm: 'Eliminar Mi Cuenta',
    language: 'Idioma',
    passwordUpdated: 'Contraseña actualizada exitosamente',
    passwordsDontMatch: 'Las contraseñas no coinciden',
    accountDeleted: 'Cuenta eliminada exitosamente',
    
    // Help
    helpTitle: 'Ayuda & Preguntas Frecuentes',
    helpQuestion1: '¿Qué es Drivers Chat?',
    helpAnswer1: 'Drivers Chat es una plataforma social diseñada específicamente para conductores profesionales para conectarse, compartir experiencias y comunicarse entre sí.',
    helpQuestion2: '¿Cómo creo una publicación?',
    helpAnswer2: 'Toca el botón + en la pantalla de inicio. Puedes escribir texto, agregar fotos y elegir quién puede ver tu publicación (Público, Amigos o Amigos específicos).',
    helpQuestion3: '¿Qué son los me gusta y no me gusta?',
    helpAnswer3: 'Puedes dar me gusta (👍) o no me gusta (👎) a publicaciones y comentarios. Si una publicación recibe 10 o más no me gusta y los no me gusta superan los me gusta, se eliminará automáticamente.',
    helpQuestion4: '¿Cómo agrego amigos?',
    helpAnswer4: 'Ve a la pestaña Amigos, busca usuarios y envíales una solicitud de amistad. Una vez aceptada, puedes compartir publicaciones con ellos.',
    helpQuestion5: '¿Qué es un código de referencia?',
    helpAnswer5: 'Tu código de referencia único puede compartirse con otros conductores. ¡Cuando se registren usando tu código, ambos se beneficiarán de estar conectados!',
    helpQuestion6: '¿Cómo cambio mi foto de perfil?',
    helpAnswer6: 'Ve a la pestaña Perfil y toca tu foto de perfil para subir una nueva foto.',
    helpQuestion7: '¿Cómo contacto con soporte?',
    helpAnswer7: 'Para soporte, envíanos un correo a support@drvchat.com',
    helpHowCanWeHelp: '¿Cómo podemos ayudarte?',
    helpFindAnswers: 'Encuentra respuestas a preguntas comunes sobre Drivers Chat',
    helpStillNeed: '¿Aún necesitas ayuda?',
    helpContactUs: 'Contáctanos en',
    
    // Help Categories
    helpCategoryAccount: 'Cuenta & Perfil',
    helpCategoryFriends: 'Sistema de Amigos',
    helpCategoryPosts: 'Publicaciones & Compartir',
    helpCategoryMessages: 'Mensajería',
    helpCategoryOther: 'Otro',
    
    // Help Q&A - Account
    helpQ1: '¿Cómo me registro?',
    helpA1: 'En la pantalla de registro, ingresa tu nombre de usuario, correo electrónico, contraseña y nombre completo. También puedes ingresar un código de referencia si tienes uno. Haz clic en "Registrarse" para crear tu cuenta.',
    helpQ2: '¿Cómo cambio mi foto de perfil?',
    helpA2: 'Ve a la pestaña Perfil, toca tu foto de perfil y selecciona una nueva foto de tu galería. La foto se recortará en un cuadrado y se subirá automáticamente.',
    helpQ3: '¿Qué es un código de referencia?',
    helpA3: 'Un código de referencia es tu código único que se muestra en tu página de perfil. Compártelo con amigos para que puedan ingresarlo al registrarse. Verás cuántas personas se unieron usando tu código.',
    helpQ4: '¿Cómo restablezco mi contraseña?',
    helpA4: 'En la pantalla de inicio de sesión, haz clic en "¿Olvidaste tu contraseña?", ingresa tu correo electrónico y nombre de usuario, y sigue las instrucciones para restablecer tu contraseña.',
    
    // Help Q&A - Friends
    helpQ5: '¿Cómo agrego amigos?',
    helpA5: 'Ve a la pestaña Amigos, usa la barra de búsqueda para encontrar usuarios por nombre de usuario o nombre, luego toca "Agregar Amigo" para enviar una solicitud de amistad. También puedes agregar un mensaje personal.',
    helpQ6: '¿Cómo acepto solicitudes de amistad?',
    helpA6: 'Ve a la pestaña Amigos y verifica la sección "Solicitudes de Amistad". Verás una insignia en el ícono de la pestaña Amigos si tienes solicitudes pendientes. Toca "Aceptar" o "Rechazar" para cada solicitud.',
    helpQ7: '¿Puedo eliminar amigos?',
    helpA7: 'Actualmente, la función de eliminación de amigos no está disponible. Esta función se agregará en futuras actualizaciones.',
    helpQ8: '¿Dónde puedo ver mi lista de amigos?',
    helpA8: 'Ve a la pestaña Amigos y desplázate hacia abajo para ver tu lista completa de amigos con sus fotos de perfil y nombres.',
    
    // Help Q&A - Posts
    helpQ9: '¿Cómo creo una publicación?',
    helpA9: 'En la pestaña Inicio, toca el ícono "+" en la parte superior derecha. Escribe tu contenido, opcionalmente agrega una foto, elige la configuración de privacidad y toca "Publicar".',
    helpQ10: '¿Qué son las configuraciones de privacidad?',
    helpA10: 'Al crear una publicación, puedes elegir:\n• Público: Todos pueden ver\n• Amigos: Solo tus amigos pueden ver\n• Específico: Elige amigos específicos que puedan ver la publicación',
    helpQ11: '¿Cómo funciona Me gusta/No me gusta?',
    helpA11: 'Puedes dar me gusta 👍 o no me gusta 👎 a cualquier publicación excepto la tuya. Toca el pulgar hacia arriba para dar me gusta o el pulgar hacia abajo para no me gusta. Puedes cambiar tu voto en cualquier momento.',
    helpQ12: '¿Qué pasa si una publicación recibe demasiados no me gusta?',
    helpA12: 'Si una publicación recibe más de 10 votos totales y más del 50% son no me gusta, se eliminará automáticamente para mantener la calidad del contenido.',
    helpQ13: '¿Puedo votar en mis propias publicaciones?',
    helpA13: 'No, no puedes dar me gusta o no me gusta a tus propias publicaciones. Los botones de votación estarán deshabilitados (en gris) en tus publicaciones.',
    helpQ14: '¿Cómo veo el perfil de alguien?',
    helpA14: 'Toca cualquier nombre de usuario o foto de perfil en publicaciones o la lista de amigos para ver su perfil y ver todas sus publicaciones.',
    
    // Help Q&A - Messages
    helpQ15: '¿Cómo funciona la Sala de Chat?',
    helpA15: 'La Sala de Chat es un espacio público donde todos los usuarios pueden chatear en tiempo real. Ve a la pestaña Sala de Chat y comienza a enviar mensajes. ¡Todos pueden ver y participar!',
    helpQ16: '¿Puedo eliminar mis mensajes de chat?',
    helpA16: '¡Sí! Puedes eliminar tus propios mensajes tocando el ícono de basura en tu mensaje. Los administradores también pueden eliminar cualquier mensaje o limpiar todo el chat.',
    helpQ17: '¿Cómo creo o me uno a grupos?',
    helpA17: 'Ve a la pestaña Grupos, toca el botón + para crear un grupo. Puedes unirte a grupos públicos directamente o solicitar unirte a grupos privados que requieren aprobación.',
    helpQ18: '¿Puedo compartir publicaciones en grupos?',
    helpA18: '¡Sí! Los miembros del grupo pueden compartir publicaciones con imágenes y emojis al grupo. Todas las publicaciones del grupo admiten me gusta, no me gusta, reacciones con emoji y comentarios.',
    
    // Help Q&A - Other
    helpQ19: '¿Cómo cierro sesión?',
    helpA19: 'Ve a la pestaña Perfil, desplázate hacia abajo y toca "Cerrar Sesión". Tu sesión terminará inmediatamente y serás redirigido a la pantalla de inicio de sesión.',
    helpQ20: '¿Puedo editar mis publicaciones?',
    helpA20: '¡Sí! Toca el ícono de editar (lápiz) en tu publicación para editar el contenido.',
    helpQ21: '¿Mis datos están seguros?',
    helpA21: '¡Sí! Tu contraseña está encriptada y todas las comunicaciones API están seguras. Nunca compartimos tu información personal con terceros.',
    helpQ22: '¿Puedo usar la aplicación sin conexión?',
    helpA22: 'No, esta aplicación requiere una conexión a internet para cargar publicaciones, enviar mensajes y realizar todas las acciones.',
    helpQ23: '¿Quién puede ver mi perfil?',
    helpA23: 'Todos los usuarios registrados pueden ver tu perfil básico (nombre, nombre de usuario, foto de perfil, publicaciones). Solo los amigos pueden ver publicaciones marcadas como "Solo amigos".',
    
    // Settings page
    settingsEditProfile: 'Editar Perfil',
    settingsNameBio: 'Nombre, Bio',
    settingsSecurity: 'Seguridad',
    settingsUpdatePassword: 'Actualiza tu contraseña',
    settingsNotifications: 'Notificaciones',
    settingsFriendRequests: 'Solicitudes de Amistad',
    settingsGetNotifiedRequests: 'Recibir notificaciones de nuevas solicitudes',
    settingsGetNotifiedMessages: 'Recibir notificaciones de nuevos mensajes',
    settingsLikes: 'Me Gusta',
    settingsGetNotifiedLikes: 'Recibir notificaciones cuando alguien le guste tu publicación',
    settingsGetNotifiedComments: 'Recibir notificaciones de nuevos comentarios en tus publicaciones',
    notificationsDisabledWarning: 'Las notificaciones push están deshabilitadas. Habilítalas en la configuración del dispositivo para recibir alertas.',
    settingsGeneral: 'General',
    settingsDarkMode: 'Modo Oscuro',
    settingsComingSoon: 'Próximamente',
    settingsDangerZone: 'Zona Peligrosa',
    settingsDeleteAccount: 'Eliminar Cuenta',
    settingsPermanentlyDelete: 'Eliminar permanentemente tu cuenta',
    settingsProfile: 'Perfil',
    settingsSaving: 'Guardando...',
    settingsChanging: 'Cambiando...',
    settingsChange: 'Cambiar',
    settingsEnterName: 'Ingresa tu nombre',
    settingsBio: 'Bio',
    settingsTellAboutYourself: 'Cuéntanos sobre ti',
    settingsEmailReadOnly: 'Correo (Solo lectura)',
    settingsEmailCannotChange: 'El correo no se puede cambiar',
    settingsEnterCurrentPassword: 'Ingresa tu contraseña actual',
    settingsEnterNewPassword: 'Ingresa tu nueva contraseña',
    settingsReenterNewPassword: 'Vuelve a ingresar tu nueva contraseña',
    settingsPasswordMinChars: 'La contraseña debe tener al menos 6 caracteres',
    settingsLanguageChanged: 'Idioma Cambiado',
    settingsLanguageSetTo: 'Idioma configurado a:',
    settingsDeleteAccountQuestion: '¿Eliminar Cuenta?',
    settingsDeleteWarning: 'Esta acción no se puede deshacer. Todas tus publicaciones, mensajes y datos serán eliminados permanentemente.',
    settingsTypeDelete: 'Escribe',
    settingsToConfirm: 'para confirmar:',
    settingsTypeDeleteHere: 'Escribe DELETE aquí',
    settingsDeleteForever: 'Eliminar Para Siempre',
    settingsNameCannotEmpty: 'El nombre no puede estar vacío',
    settingsProfileUpdated: '¡Perfil actualizado exitosamente!',
    settingsFailedUpdateProfile: 'Error al actualizar perfil',
    settingsNewPasswordsNoMatch: 'Las nuevas contraseñas no coinciden',
    settingsFailedChangePassword: 'Error al cambiar contraseña',
    settingsPasswordChanged: '¡Contraseña cambiada exitosamente!',
    settingsAccountDeleted: 'Tu cuenta ha sido eliminada permanentemente',
    settingsFailedDeleteAccount: 'Error al eliminar cuenta',
    settingsPleaseTypeDelete: 'Por favor escribe DELETE para confirmar',
    
    // Messages/Chat
    messagesNoMessagesYet: 'Aún no hay mensajes',
    messagesStartChatting: '¡Comienza a chatear!',
    messagesNewChat: 'Nuevo Chat',
    
    // Friends
    friendsTitle: 'Amigos',
    friendsSearchDrivers: 'Buscar conductores...',
    friendsFriendRequests: 'Solicitudes de Amistad',
    friendsMyFriends: 'Mis Amigos',
    friendsNoFriendsYet: 'Aún no tienes amigos',
    friendsSearchAddFriends: '¡Busca y agrega amigos arriba!',
    friendsFriendRequestSent: '¡Solicitud de amistad enviada!',
    friendsFailedSendRequest: 'Error al enviar solicitud',
    friendsFriendAdded: '¡Amigo agregado!',
    friendsRequestRejected: 'Solicitud rechazada',
    friendsActionFailed: 'Acción fallida',
    
    // Forgot Password
    forgotPasswordTitle: 'Olvidé mi Contraseña',
    forgotPasswordInstruction: 'Ingresa tu correo y nombre de usuario para restablecer tu contraseña',
    forgotPasswordResetButton: 'Restablecer Contraseña',
    forgotPasswordCheckEmail: 'Revisa tu Correo',
    forgotPasswordEmailSent: 'Las instrucciones para restablecer la contraseña han sido enviadas a tu correo.',
    forgotPasswordBackToLogin: 'Volver al Inicio de Sesión',
    forgotPasswordFailed: 'Error al enviar correo de restablecimiento',
    
    // Post Detail
    postDetailComments: 'Comentarios',
    postDetailNoComments: 'Aún no hay comentarios',
    postDetailBeFirst: '¡Sé el primero en comentar!',
    postDetailWriteComment: 'Escribe un comentario...',
    postDetailSendComment: 'Enviar',
    postDetailCommentPosted: '¡Comentario publicado!',
    postDetailFailedComment: 'Error al publicar comentario',
    
    // Profile Detail
    profileDetailSendMessage: 'Enviar Mensaje',
    profileDetailAddFriend: 'Agregar Amigo',
    profileDetailPosts: 'Publicaciones',
    profileDetailNoPosts: 'Aún no hay publicaciones',
    
    // Referral Share
    shareReferralCode: 'Compartir Código de Referencia',
    nextStarIn: 'Próxima estrella en',
    referrals: 'referencias',
    
    // Edit Post Modal
    editPostSaveChanges: 'Guardar Cambios',
    
    // Full Screen Image
    fullScreenImageClose: 'Cerrar',
    
    // Search
    searchPosts: 'Buscar publicaciones...',
    searchResults: 'Resultados de Búsqueda',
    noResultsFound: 'No se encontraron resultados',
    searching: 'Buscando...',
    
    // Comments
    comments: 'Comentarios',
    viewAllComments: 'Ver todos los comentarios',
    writeComment: 'Escribe un comentario...',
    noComments: 'Aún no hay comentarios',
    
    // Block User
    blockUser: 'Bloquear Usuario',
    unblockUser: 'Desbloquear Usuario',
    blockedUsers: 'Usuarios Bloqueados',
    blockUserConfirm: '¿Estás seguro de que quieres bloquear a este usuario? No verás sus publicaciones ni mensajes.',
    unblockUserConfirm: '¿Estás seguro de que quieres desbloquear a este usuario?',
    userBlocked: 'Usuario bloqueado exitosamente',
    userUnblocked: 'Usuario desbloqueado exitosamente',
    noBlockedUsers: 'No hay usuarios bloqueados',
    
    // Report System
    reportPost: 'Reportar Publicación',
    reportUser: 'Reportar Usuario',
    reportComment: 'Reportar Comentario',
    selectReason: 'Selecciona una razón',
    spam: 'Spam',
    harassment: 'Acoso',
    inappropriate: 'Contenido Inapropiado',
    hateSpeech: 'Discurso de Odio',
    violence: 'Violencia',
    other: 'Otro',
    additionalDetails: 'Detalles adicionales (opcional)',
    submitReport: 'Enviar Reporte',
    reportSubmitted: 'Reporte enviado exitosamente',
    reportFailed: 'Error al enviar reporte',
    reports: 'Reportes',
    pending: 'Pendiente',
    reviewed: 'Revisado',
    resolved: 'Resuelto',
    dismissed: 'Desestimado',
    
    // About
    aboutTitle: 'Acerca de Drivers Chat',
    aboutDescription: 'Drivers Chat es una plataforma comunitaria construida por conductores, para conductores. Conéctate con otros conductores profesionales, comparte tus experiencias y construye conexiones significativas.',
    aboutVersion: 'Versión',
    aboutSupport: 'Soporte',
    aboutTerms: 'Términos y Condiciones',
    viewTerms: 'Ver Términos y Condiciones',
    
    // Terms Modal
    termsTitle: 'Términos y Condiciones',
    termsOfService: 'Términos de Servicio',
    communityGuidelines: 'Directrices de la Comunidad',
    termsAccept: 'Acepto',
    termsDecline: 'Rechazar',
    termsStep: 'Paso',
    termsOf: 'de',
    termsAgreeService: 'He leído y acepto los Términos de Servicio',
    termsAgreeGuidelines: 'He leído y acepto seguir las Directrices de la Comunidad',
    termsContinue: 'Continuar',
    termsAcceptStart: 'Aceptar & Empezar a Usar Drivers Chat',
    termsEffectiveDate: 'Fecha de Vigencia: Enero 2025',
    termsWelcome: '¡Bienvenido a Drivers Chat! Por favor lee estos términos cuidadosamente antes de usar nuestra aplicación.',
    termsNonCommercial: 'Aplicación No Comercial',
    termsLimitationLiability: 'Limitación de Responsabilidad',
    termsYourRights: 'Tus Derechos & Control de Cuenta',
    termsDataPrivacy: 'Datos & Privacidad',
    termsAgeRequirement: 'Requisito de Edad',
    termsAccountSecurity: 'Seguridad de la Cuenta',
    termsServiceChanges: 'Cambios de Servicio & Terminación',
    termsContact: 'Contacto',
    termsSupportEmail: 'support@drvchat.com',
    guidelinesKeepSafe: 'Mantén Drivers Chat Seguro & Respetuoso',
    guidelinesIntro: 'Estas directrices aseguran una experiencia positiva para todos los miembros. Las violaciones resultarán en suspensión de cuenta o prohibición permanente.',
    guidelinesProhibited: 'Contenido Estrictamente Prohibido',
    guidelinesConsequences: 'Consecuencias',
    guidelinesWhatYouCan: 'Lo Que PUEDES Compartir',
    guidelinesReport: 'Reportar Violaciones',
    
    // About page
    aboutWherDriversConnect: 'Donde los Conductores se Conectan',
    aboutTheApp: 'Acerca de la Aplicación',
    aboutAppDescription: 'Drivers Chat es una plataforma social GRATUITA construida exclusivamente para conductores profesionales. Conéctate con otros conductores, comparte experiencias, obtén consejos y mantente informado sobre todo relacionado con conducir.',
    aboutOurMission: 'Nuestra Misión',
    aboutMissionDescription: 'Crear una comunidad de apoyo donde los conductores puedan conectarse, compartir conocimientos y ayudarse mutuamente a navegar los desafíos y oportunidades de la conducción profesional.',
    aboutKeyFeatures: 'Características Clave',
    aboutFeature1: 'Conecta con conductores a nivel nacional',
    aboutFeature2: 'Sala de chat pública - Conversaciones en tiempo real',
    aboutFeature3: 'Crea y únete a grupos de conductores',
    aboutFeature4: 'Comparte publicaciones con fotos y reacciones emoji',
    aboutFeature5: 'Sistema de recompensas por referencia',
    aboutFeature6: 'Moderación admin y comunidad segura',
    aboutFree: '100% Gratis',
    aboutFreeDescription: 'Drivers Chat es completamente gratis sin membresías pagas, funciones premium o costos ocultos. Esta es una plataforma no comercial construida por conductores, para conductores.',
    aboutCommunityGuidelines: 'Directrices de la Comunidad',
    aboutGuidelinesDescription: 'Mantenemos un entorno seguro y respetuoso prohibiendo actividades comerciales, contenido político, apuestas, contenido para adultos, discurso de odio y actividades ilegales. Los usuarios que violen nuestras directrices enfrentan suspensión de cuenta o prohibiciones permanentes.',
    aboutReadFullTerms: 'Leer Términos & Directrices Completos →',
    aboutContactSupport: 'Contacto & Soporte',
    aboutContactDescription: '¿Tienes preguntas, comentarios o necesitas ayuda?',
    aboutEmailUs: 'Envíanos un correo a:',
    aboutVisitHelp: 'Visitar Centro de Ayuda →',
    aboutLegal: 'Legal',
    aboutTermsService: 'Términos de Servicio',
    aboutPrivacyPolicy: 'Política de Privacidad',
    aboutMadeWith: 'Hecho con ❤️ para conductores',
    aboutCopyright: '© 2025 Drivers Chat. Todos los derechos reservados.',
    aboutLegalGuidelines: 'Legal & Directrices',
    
    // Admin Panel
    adminPanel: 'Panel de Administrador',
    adminStatistics: 'Estadísticas',
    adminReports: 'Reportes',
    adminUsers: 'Usuarios',
    adminPosts: 'Publicaciones',
    adminTotalUsers: 'Total de Usuarios',
    adminTotalPosts: 'Total de Publicaciones',
    adminTotalComments: 'Total de Comentarios',
    adminTotalReports: 'Total de Reportes',
    adminPendingReports: 'Reportes Pendientes',
    adminRecentUsers: 'Nuevos Usuarios (7d)',
    adminRecentPosts: 'Nuevas Publicaciones (7d)',
    adminViewReports: 'Ver Reportes',
    adminManageUsers: 'Gestionar Usuarios',
    adminManagePosts: 'Gestionar Publicaciones',
    adminReportedBy: 'Reportado por',
    adminReportedUser: 'Usuario Reportado',
    adminReason: 'Razón',
    adminDescription: 'Descripción',
    adminStatus: 'Estado',
    adminPending: 'Pendiente',
    adminReviewed: 'Revisado',
    adminResolved: 'Resuelto',
    adminDismissed: 'Descartado',
    adminMarkReviewed: 'Marcar como Revisado',
    adminMarkResolved: 'Marcar como Resuelto',
    adminDismiss: 'Descartar',
    adminNoReports: 'No se encontraron reportes',
    adminUserList: 'Lista de Usuarios',
    adminJoined: 'Se unió',
    adminIsAdmin: 'Admin',
    adminMakeAdmin: 'Hacer Admin',
    adminRemoveAdmin: 'Quitar Admin',
    adminBanUser: 'Banear Usuario',
    adminUnbanUser: 'Desbanear Usuario',
    adminNoUsers: 'No se encontraron usuarios',
    adminPostList: 'Lista de Publicaciones',
    adminPostedBy: 'Publicado por',
    adminLikes: 'Me gusta',
    adminDislikes: 'No me gusta',
    adminComments: 'Comentarios',
    adminDeletePost: 'Eliminar Publicación',
    adminNoPosts: 'No se encontraron publicaciones',
    adminConfirmDelete: '¿Estás seguro de que quieres eliminar esta publicación?',
    adminConfirmBan: '¿Estás seguro de que quieres banear a este usuario?',
    adminConfirmUnban: '¿Estás seguro de que quieres desbanear a este usuario?',
    adminConfirmMakeAdmin: '¿Estás seguro de que quieres hacer a este usuario administrador?',
    adminConfirmRemoveAdmin: '¿Estás seguro de que quieres quitar los derechos de administrador a este usuario?',
    adminSuccess: 'Éxito',
    adminError: 'Error',
    adminSpam: 'Spam',
    adminHarassment: 'Acoso',
    adminInappropriate: 'Contenido Inapropiado',
    adminHateSpeech: 'Discurso de Odio',
    adminViolence: 'Violencia',
    adminOther: 'Otro',
    
    // Groups
    groups: 'Grupos',
    myGroups: 'Mis Grupos',
    discoverGroups: 'Descubrir Grupos',
    createGroup: 'Crear Grupo',
    groupName: 'Nombre del Grupo',
    groupDescription: 'Descripción del Grupo (opcional)',
    groupPrivacy: 'Privacidad del Grupo',
    publicGroup: 'Público - Cualquiera puede unirse',
    privateGroup: 'Privado - Requiere aprobación',
    members: 'Miembros',
    creator: 'Creador',
    joinGroup: 'Unirse al Grupo',
    leaveGroup: 'Salir del Grupo',
    deleteGroup: 'Eliminar Grupo',
    requestSent: 'Solicitud Enviada',
    joinRequests: 'Solicitudes de Unión',
    approve: 'Aprobar',
    reject: 'Rechazar',
    noGroups: 'No se encontraron grupos',
    noGroupsYet: 'Aún no te has unido a ningún grupo',
    createFirstGroup: 'Crea tu primer grupo',
    groupCreated: 'Grupo creado exitosamente',
    groupDeleted: 'Grupo eliminado exitosamente',
    leftGroup: 'Has salido del grupo exitosamente',
    joinedGroup: 'Te has unido al grupo exitosamente',
    requestApproved: 'Solicitud aprobada',
    requestRejected: 'Solicitud rechazada',
    confirmDeleteGroup: '¿Estás seguro de que quieres eliminar este grupo? Todas las publicaciones permanecerán pero ya no estarán asociadas con el grupo.',
    confirmLeaveGroup: '¿Estás seguro de que quieres salir de este grupo?',
    enterGroupName: 'Por favor ingresa un nombre de grupo',
    postToGroup: 'Publicar en el Grupo',
    groupPosts: 'Publicaciones del Grupo',
    noPostsInGroup: 'Aún no hay publicaciones en este grupo',
    shareToGroup: 'Compartir en este grupo',
    
    // Chat Room
    chatRoom: 'Sala de Chat',
    publicChat: 'Chat Público',
    everyoneCanSee: 'Todos pueden ver y enviar mensajes',
    typeMessage: 'Escribe un mensaje...',
    send: 'Enviar',
    noChatMessages: 'Aún no hay mensajes. ¡Inicia la conversación!',
    justNow: 'Ahora mismo',
    online: 'en línea',
    deleteMessage: 'Eliminar Mensaje',
    confirmDeleteMessage: '¿Estás seguro de que quieres eliminar este mensaje?',
    clearChat: 'Limpiar Chat',
    confirmClearChat: '¿Estás seguro de que quieres eliminar todos los mensajes? Esta acción no se puede deshacer.',
    disableChat: 'Desactivar Chat',
    enableChat: 'Activar Chat',
    chatDisabled: 'Chat desactivado',
    chatDisabledMessage: 'La sala de chat ha sido desactivada por el administrador',
  },
};

export const useTranslation = () => {
  const language = useLanguageStore((state) => state.language);
  
  const t = (key: keyof typeof translations.en): string => {
    return translations[language][key] || translations.en[key] || key;
  };
  
  return { t, language };
};
